### ISSUE TITLE
Failure upon GitHub installation

### ISSUE THREAD

**Issue by falexwolf** [theislab/scvelo#10]
Hey Volker!

```
(python3_backup) ubuntu@ip-172-31-35-11:~/code$ git clone https://github.com/theislab/scvelo.git
Cloning into 'scvelo'...
remote: Counting objects: 541, done.
remote: Total 541 (delta 0), reused 0 (delta 0), pack-reused 541
Receiving objects: 100% (541/541), 108.40 KiB | 0 bytes/s, done.
Resolving deltas: 100% (331/331), done.
Checking connectivity... done.
(python3_backup) ubuntu@ip-172-31-35-11:~/code$ 
(python3_backup) ubuntu@ip-172-31-35-11:~/code$ 
(python3_backup) ubuntu@ip-172-31-35-11:~/code$ cd scvelo
(python3_backup) ubuntu@ip-172-31-35-11:~/code/scvelo$ 
(python3_backup) ubuntu@ip-172-31-35-11:~/code/scvelo$ 
(python3_backup) ubuntu@ip-172-31-35-11:~/code/scvelo$ ls
docs  LICENSE  pyproject.toml  pytest.ini  README.rst  scvelo  setup.py  tests
(python3_backup) ubuntu@ip-172-31-35-11:~/code/scvelo$ 
(python3_backup) ubuntu@ip-172-31-35-11:~/code/scvelo$ pip install -e .
Obtaining file:///home/ubuntu/code/scvelo
  Missing build requirements in pyproject.toml for file:///home/ubuntu/code/scvelo.
  This version of pip does not implement PEP 517 so it cannot build a wheel without 'setuptools' and 'wheel'.
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/code/scvelo/setup.py", line 60, in <module>
        setup()
      File "/home/ubuntu/code/scvelo/setup.py", line 25, in setup
        metadata = common.make_metadata(module, ini_info)
      File "/tmp/pip-build-env-ifv505m8/lib/python3.6/site-packages/flit/common.py", line 305, in make_metadata
        md_dict.update(get_info_from_module(module))
      File "/tmp/pip-build-env-ifv505m8/lib/python3.6/site-packages/flit/common.py", line 111, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "/tmp/pip-build-env-ifv505m8/lib/python3.6/site-packages/flit/common.py", line 95, in get_docstring_and_version_via_import
        m = sl.load_module()
      File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 823, in load_module
      File "<frozen importlib._bootstrap_external>", line 682, in load_module
      File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "scvelo/__init__.py", line 3, in <module>
        from get_version import get_version
    ModuleNotFoundError: No module named 'get_version'
```

I tried fixing it by setting the line
```
from ._version import get_versions
```
as in Scanpy (added by versioneer). But this still fails. I then figured that you haven't committed any versioneer files to GitHub, it seems. Maybe it's just that.

**Comment by VolkerBergen** [comment]
Thanks for trying to solve that issue! :) It should be fixed now.
