### ISSUE TITLE
scv.read: OSError: Unable to open file

### ISSUE THREAD

**Issue by GBeattie** [theislab/scvelo#102]
Hey!

I am trying to read in my seurat generated loom file (as.loom) and am getting the following error:

`OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')`

Googling the error implies it's a h5df issue, but I have the most recent h5df release. Doesn't help that i'm a python novice so a more in depth fix is beyond my reach!

Thanks in advance for any assistance, command and full error output below (note, scv.read is working for a velocyto outputted .loom).

`adata_seu = scv.read('./UT/wt_UT_combined.loom')`
```
Traceback (most recent call last):

  File "<ipython-input-21-657de7fa93a9>", line 1, in <module>
    adata_seu = scv.read('./UT/wt_UT_combined.loom')

  File "/opt/miniconda3/lib/python3.7/site-packages/scanpy/readwrite.py", line 97, in read
    backup_url=backup_url, cache=cache, **kwargs,

  File "/opt/miniconda3/lib/python3.7/site-packages/scanpy/readwrite.py", line 542, in _read
    adata = read_loom(filename=filename, **kwargs)

  File "/opt/miniconda3/lib/python3.7/site-packages/anndata/readwrite/read.py", line 157, in read_loom
    with connect(filename, 'r', **kwargs) as lc:

  File "/opt/miniconda3/lib/python3.7/site-packages/loompy/loompy.py", line 1389, in connect
    return LoomConnection(filename, mode, validate=validate)

  File "/opt/miniconda3/lib/python3.7/site-packages/loompy/loompy.py", line 81, in __init__
    if not lv.validate(filename):

  File "/opt/miniconda3/lib/python3.7/site-packages/loompy/loom_validator.py", line 48, in validate
    with h5py.File(path, mode="r") as f:

  File "/opt/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)

  File "/opt/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5f.pyx", line 88, in h5py.h5f.open

OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
```

**Comment by GBeattie** [comment]
Error fixed itself after restart!
