### ISSUE TITLE
ValueError: setting an array element with a sequence. 

### ISSUE THREAD

**Issue by KunFang93** [theislab/scvelo#1077]
Hi,

I am a fresh user of scvelo and thanks for providing this useful tool! I run into this bug
```
Traceback (most recent call last):
  File "/Users/kfang/miniconda3/envs/scvelo/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-595fdc5ca577>", line 1, in <module>
    scv.tl.velocity_graph(adata, n_jobs=1)
  File "/Users/kfang/miniconda3/envs/scvelo/lib/python3.9/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/kfang/miniconda3/envs/scvelo/lib/python3.9/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "/Users/kfang/miniconda3/envs/scvelo/lib/python3.9/site-packages/scvelo/core/_parallelize.py", line 138, in wrapper
    res = np.array(res) if as_array else res
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
```
and wondered how I could solve this.

My codes is
```
import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np
import pandas as pd
import anndata as ad

datdir = '/Users/kfang/Documents/lab/Jin_lab/scRNA_scATAC/scRNA/results/scvelo'
scv.settings.verbosity = 3
scv.settings.set_figure_params('scvelo', facecolor='white', dpi=100, frameon=False)
cr.settings.verbosity = 2
adata = sc.read_h5ad(f'{datdir}/my_data.h5ad')
adata.obs['seurat_clusters'] = adata.obs['seurat_clusters'].astype('category')
# load loom files for spliced/unspliced matrices for each sample:
ldata_pt1 = scv.read(f'{datdir}/PT1.loom', cache=True)
ldata_pt2 = scv.read(f'{datdir}/PT2.loom', cache=True)
ldata_pt3 = scv.read(f'{datdir}/PT5.loom', cache=True)
ldata_rt1 = scv.read(f'{datdir}/RT3.loom', cache=True)
ldata_rt2 = scv.read(f'{datdir}/RT4.loom', cache=True)
ldata_rt3 = scv.read(f'{datdir}/RT6.loom', cache=True)

# rename barcodes in order to merge:
pt1_barcodes = [bc.split(':')[1] for bc in ldata_pt1.obs.index.tolist()]
pt1_barcodes = ['PT1_' + bc[0:len(bc)-1] + '-1' for bc in pt1_barcodes]
pt2_barcodes = [bc.split(':')[1] for bc in ldata_pt2.obs.index.tolist()]
pt2_barcodes = ['PT2_' + bc[0:len(bc)-1] + '-1' for bc in pt2_barcodes]
pt3_barcodes = [bc.split(':')[1] for bc in ldata_pt3.obs.index.tolist()]
pt3_barcodes = ['PT3_' + bc[0:len(bc)-1] + '-1' for bc in pt3_barcodes]
rt1_barcodes = [bc.split(':')[1] for bc in ldata_rt1.obs.index.tolist()]
rt1_barcodes = ['RT1_' + bc[0:len(bc)-1] + '-1' for bc in rt1_barcodes]
rt2_barcodes = [bc.split(':')[1] for bc in ldata_rt2.obs.index.tolist()]
rt2_barcodes = ['RT2_' + bc[0:len(bc)-1] + '-1' for bc in rt2_barcodes]
rt3_barcodes = [bc.split(':')[1] for bc in ldata_rt3.obs.index.tolist()]
rt3_barcodes = ['RT3_' + bc[0:len(bc)-1] + '-1' for bc in rt3_barcodes]
ldata_pt1.obs.index = pt1_barcodes
ldata_pt2.obs.index = pt2_barcodes
ldata_pt3.obs.index = pt3_barcodes
ldata_rt1.obs.index = rt1_barcodes
ldata_rt2.obs.index = rt2_barcodes
ldata_rt3.obs.index = rt3_barcodes

# make variable names unique
ldata_pt1.var_names_make_unique()
ldata_pt2.var_names_make_unique()
ldata_pt3.var_names_make_unique()
ldata_rt1.var_names_make_unique()
ldata_rt2.var_names_make_unique()
ldata_rt3.var_names_make_unique()

# extract cancer cells
cancer_meta = adata.obs
cancer_meta['sample'] = cancer_meta['barcode'].str.split('_',expand=True)[0]
ldata_pt1_cancer = ldata_pt1[cancer_meta.loc[cancer_meta['sample']=='PT1','barcode'].values,]
ldata_pt2_cancer = ldata_pt2[cancer_meta.loc[cancer_meta['sample']=='PT2','barcode'].values,]
ldata_pt3_cancer = ldata_pt3[cancer_meta.loc[cancer_meta['sample']=='PT3','barcode'].values,]
ldata_rt1_cancer = ldata_rt1[cancer_meta.loc[cancer_meta['sample']=='RT1','barcode'].values,]
ldata_rt2_cancer = ldata_rt2[cancer_meta.loc[cancer_meta['sample']=='RT2','barcode'].values,]
ldata_rt3_cancer = ldata_rt3[cancer_meta.loc[cancer_meta['sample']=='RT3','barcode'].values,]

# concatenate the three loom
ldata = ldata_pt1_cancer.concatenate([ldata_pt2_cancer, ldata_pt3_cancer, ldata_rt1_cancer,
                                      ldata_rt2_cancer, ldata_rt3_cancer])
# merge matrices into the original adata object
scv.utils.clean_obs_names(adata)
scv.utils.clean_obs_names(ldata)
adata = scv.utils.merge(adata, ldata)
# plot umap to check
# plot umap to check

sc.pl.umap(adata, color='seurat_clusters', frameon=False, legend_loc='on data', title='', save='_celltypes.pdf')
# compute RNA velocity using the steady-state model (stochastic option)
scv.pl.proportions(adata, groupby='seurat_clusters')

# pre-process
scv.pp.filter_and_normalize(adata)
scv.pp.moments(adata)

# compute velocity
scv.tl.velocity(adata, mode='stochastic')
scv.tl.velocity_graph(adata, n_jobs=1)
```

Thanks in advance!

Best,
Kun

**Comment by WeilerP** [comment]
Already reported previously, and fixed in #1059. Please search issues before opening a new one.
