### ISSUE TITLE
scv.pl.velocity_embedding_stream() - AttributeError: can't set attribute

### ISSUE THREAD

**Issue by colin893** [theislab/scvelo#1091]
Created a conda environment with cellrank and all required modules, followed the tutorial to be sure everything was fine but got an error at the very last command : AttributeError: can't set attribute

```python
mport sys
import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np

scv.settings.verbosity = 3
scv.settings.set_figure_params("scvelo")
cr.settings.verbosity = 2

import warnings

warnings.simplefilter("ignore", category=UserWarning)
warnings.simplefilter("ignore", category=FutureWarning)
warnings.simplefilter("ignore", category=DeprecationWarning)

adata = cr.datasets.pancreas()
scv.pl.proportions(adata)
adata

scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
sc.tl.pca(adata)
sc.pp.neighbors(adata, n_pcs=30, n_neighbors=30)
scv.pp.moments(adata, n_pcs=None, n_neighbors=None)

scv.tl.recover_dynamics(adata, n_jobs=8)

scv.tl.velocity(adata, mode="dynamical")
scv.tl.velocity_graph(adata)

scv.tl.velocity(adata, mode="dynamical")
scv.tl.velocity_graph(adata)

scv.pl.velocity_embedding_stream(
adata, basis="umap", legend_fontsize=12, title="", smooth=0.8, min_mass=4
)

```

```pytb
scv.pl.velocity_embedding_stream(
... adata, basis="umap", legend_fontsize=12, title="", smooth=0.8, min_mass=4 
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/velocity_embedding_stream.py", line 252, in velocity_embedding_stream
    ax = scatter(
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/scatter.py", line 668, in scatter
    set_legend(
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/utils.py", line 555, in set_legend
    obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/base.py", line 178, in __setattr__
    object.__setattr__(self, key, value)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/accessor.py", line 99, in _setter
    return self._delegate_property_set(name, new_values)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 2460, in _delegate_property_set
    return setattr(self._parent, name, new_values)
AttributeError: can't set attribute
```

#### Versions:

#> >>> cellrank.logging.print_versions()
cellrank==1.5.1 scanpy==1.9.3 anndata==0.9.1 numpy==1.21.6 numba==0.57.0 scipy==1.11.0 pandas==2.0.2 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by zhouzhendiao** [comment]
I also encountered `AttributeError` when running the [tutorial](https://scvelo.readthedocs.io/en/stable/VelocityBasics/). `scv.pl.velocity_embedding_stream` failed to annotated cluster to umap. I think this error related to the dtype which is catogory, because no error when annotating continuous value(float dtype).

```
scv.pl.velocity_embedding_stream(adata, basis='umap', color=['clusters'])
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[63], line 1
----> 1 scv.pl.velocity_embedding_stream(adata, basis='umap', color=['clusters'])

File /opt/conda/lib/python3.10/site-packages/scvelo/plotting/velocity_embedding_stream.py:252, in velocity_embedding_stream(adata, basis, vkey, density, smooth, min_mass, cutoff_perc, arrow_color, arrow_size, arrow_style, max_length, integration_direction, linewidth, n_neighbors, recompute, color, use_raw, layer, color_map, colorbar, palette, size, alpha, perc, X, V, X_grid, V_grid, sort_order, groups, components, legend_loc, legend_fontsize, legend_fontweight, xlabel, ylabel, title, fontsize, figsize, dpi, frameon, show, save, ax, ncols, **kwargs)
    249 ax.streamplot(X_grid[0], X_grid[1], V_grid[0], V_grid[1], **stream_kwargs)
    251 size = 8 * default_size(adata) if size is None else size
--> 252 ax = scatter(
    253     adata,
    254     layer=layer,
    255     color=color,
    256     size=size,
    257     title=title,
    258     ax=ax,
    259     zorder=0,
    260     **scatter_kwargs,
    261 )
    262 if save is True:
    263     save = "embedding_stream"

File /opt/conda/lib/python3.10/site-packages/scvelo/plotting/scatter.py:668, in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, legend_align_text, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_margin, add_outline, outline_width, outline_color, n_convolve, smooth, normalize_data, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    666     if not (add_outline is None or g_bool is None):
    667         groups = add_outline
--> 668     set_legend(
    669         adata,
    670         ax,
    671         color,
    672         legend_loc,
    673         scatter_array,
    674         legend_fontweight,
    675         legend_fontsize,
    676         legend_fontoutline,
    677         legend_align_text,
    678         groups,
    679     )
    680 if add_density:
    681     plot_density(x, y, add_density, ax=ax)

File /opt/conda/lib/python3.10/site-packages/scvelo/plotting/utils.py:555, in set_legend(adata, ax, value_to_plot, legend_loc, scatter_array, legend_fontweight, legend_fontsize, legend_fontoutline, legend_align_text, groups)
    553     legend_fontoutline = 1
    554 obs_vals = adata.obs[value_to_plot]
--> 555 obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
    556 color_keys = adata.uns[f"{value_to_plot}_colors"]
    557 if isinstance(color_keys, dict):

File /opt/conda/lib/python3.10/site-packages/pandas/core/base.py:178, in NoNewAttributesMixin.__setattr__(self, key, value)
    172 if getattr(self, "__frozen", False) and not (
    173     key == "_cache"
    174     or key in type(self).__dict__
    175     or getattr(self, key, None) is not None
    176 ):
    177     raise AttributeError(f"You cannot add any new attribute '{key}'")
--> 178 object.__setattr__(self, key, value)

File /opt/conda/lib/python3.10/site-packages/pandas/core/accessor.py:99, in PandasDelegate._add_delegate_accessors.<locals>._create_delegator_property.<locals>._setter(self, new_values)
     98 def _setter(self, new_values):
---> 99     return self._delegate_property_set(name, new_values)

File /opt/conda/lib/python3.10/site-packages/pandas/core/arrays/categorical.py:2460, in CategoricalAccessor._delegate_property_set(self, name, new_values)
   2459 def _delegate_property_set(self, name, new_values):
-> 2460     return setattr(self._parent, name, new_values)

AttributeError: can't set attribute 'categories'
```

Did you solve this issue? @colin893

**Comment by Marius1311** [comment]
Try installing scVelo from main.
