### ISSUE TITLE
tl.velocity_graph Keeps Restarting SubProcess Causing an Error To Throw

### ISSUE THREAD

**Issue by DevonJBoland** [theislab/scvelo#1095]
I am trying to use scVelo to process matrix data from Alevin-Fry to compute RNA velocities for a scRNA-seq project. I am following the tutorial outlined here: [](https://scvelo.readthedocs.io/en/stable/VelocityBasics/)

The Alevin-fry data has no issue being loaded, and the PCA, Neighbors, tSNE, UMAP, and scv.pp.moments has no issue running. When the velocity_graph is being caluclated the following error keeps occurring. Looking at older issues I have tried change the versions of packages that have seemed to work for other users, including `umap-learn` and `numba` as mentioned in [](https://github.com/scverse/scanpy/issues/1756) for scanpy to see if that resolved the issue.
...

```python
#!/Users/devonboland/miniconda3/bin/python3

import numpy as np
import pandas as pd
import scanpy as sc
import anndata
import scvelo as scv
import matplotlib
import scipy
from pyroe import load_fry
import os

frydir = "Alevin/1_c_dcr_quant_res"
e2n_path = "Alevin/refdata-gex-mm10-2020-A/genes/mm10-2020-A_geneid_to_name.txt"
adata = load_fry(frydir, output_format = "velocity")
e2n = dict([ l.rstrip().split() for l in open(e2n_path).readlines()])
adata.var_names = [e2n[e] for e in adata.var_names]

# make sure gene names are unique
adata.var_names_make_unique()

# get embeddings
sc.tl.pca(adata)
sc.pp.neighbors(adata)
sc.tl.tsne(adata)
sc.tl.umap(adata, n_components = 2)

# housekeeping
matplotlib.use('AGG')
scv.settings.set_figure_params('scvelo')

# get the proportion of spliced and unspliced count
scv.utils.show_proportions(adata)


# filter cells and genes, then normalize expression values
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000,enforce=True)

# scVelo pipeline
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.velocity(adata)
scv.tl.velocity_graph(adata)
adata.write('1_c_dcr.h5ad', compression='gzip')
scv.pl.velocity_embedding_stream(adata, basis='X_umap', save="pancreas_full_dim.png")
```

<details>

<summary> Error output </summary>

```pytb
USA mode: True
Using pre-defined output format: velocity
Will populate output field X with sum of counts frorm ['S', 'A'].
Will combine ['S', 'A'] into output layer spliced.
Will combine ['U'] into output layer unspliced.
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Abundance of ['unspliced', 'spliced']: [0.56 0.44]
Filtered out 26707 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Extracted 2000 highly variable genes.
Logarithmized X.
WARNING: You seem to have 5 duplicate cells in your data. Consider removing these via pp.remove_duplicate_cells.
computing neighbors
    finished (0:00:00) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/12 cores)
  0%|          | 0/897 [00:00<?, ?cells/s]
USA mode: True
Using pre-defined output format: velocity
Will populate output field X with sum of counts frorm ['S', 'A'].
Will combine ['S', 'A'] into output layer spliced.
Will combine ['U'] into output layer unspliced.
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Abundance of ['unspliced', 'spliced']: [0.56 0.44]
Filtered out 26707 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Extracted 2000 highly variable genes.
Logarithmized X.
WARNING: You seem to have 5 duplicate cells in your data. Consider removing these via pp.remove_duplicate_cells.
computing neighbors
    finished (0:00:00) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/12 cores)
  0%|          | 0/897 [00:00<?, ?cells/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/devonboland/miniconda3/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/devonboland/miniconda3/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/devonboland/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Volumes/DevonFiles/TIGSS/Sarkar_scRNA/scVelo.py", line 42, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/managers.py", line 562, in start
    self._process.start()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Volumes/DevonFiles/TIGSS/Sarkar_scRNA/scVelo.py", line 42, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "/Users/devonboland/miniconda3/lib/python3.10/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/managers.py", line 566, in start
    self._address = reader.recv()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/devonboland/miniconda3/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

</details>

<details> <summary> Versions </summary>

```pytb
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
scvelo==0.2.5  scanpy==1.9.3  anndata==0.9.1  loompy==3.0.7  numpy==1.21.5  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.3.0  pandas==1.5.3  
```

</details>

**Comment by WeilerP** [comment]
@DevonJBoland, this seems to be an issue with multiprocessing, not scvelo. Can you please check if the code runs in Python 3.9?

**Comment by Baschdl** [comment]
We encountered this problem on the Pancreas dataset. Strangely, it fails when running it as a script but it works in a Jupyter notebook.

**Comment by WeilerP** [comment]
Closing this issue as it seems unrelated to scvelo itself but rather multiprocessing and the OS.
