### ISSUE TITLE
Installed from origin/master, scvelo will not load

### ISSUE THREAD

**Issue by c5creative** [theislab/scvelo#1123]
Greetings, I'm trying to install the latest scVelo (since 0.25 errors out on various functions and the issues I've read are pointing me to install from master (0.3.0-ish). Trying (attempt #5 or 6, losing track now) of installing scVelo, and 
Linux system (in conda env)
Python 3.8.18

I've spent 5-6 hours on this already. The docs are out of date, there's no clear way to get this installed - would love to get insight from others who have been more successful than me! Thanks!!!

#### Installation, step 1

```bash
# installation
conda create -n scvelo_py38 python=3.8

# then activate and from within conda env:
pip install git+https://github.com/theislab/scvelo
```
If I try to import `scvelo` at this point, I'll get:
<details>
```pytb
>>> import scvelo
Global seed set to 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/__init__.py", line 6, in <module>
    from scvelo import plotting as pl
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/__init__.py", line 3, in <module>
    from .gridspec import gridspec
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/gridspec.py", line 6, in <module>
    from .scatter import scatter
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/scatter.py", line 16, in <module>
    from .utils import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/utils.py", line 24, in <module>
    from scvelo.tools.utils import strings_to_categoricals
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/tools/__init__.py", line 14, in <module>
    from ._vi_model import VELOVI
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/tools/_vi_model.py", line 14, in <module>
    from scvi.data import AnnDataManager
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/__init__.py", line 10, in <module>
    from . import autotune, data, model, external, utils
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/autotune/__init__.py", line 1, in <module>
    from ._manager import TuneAnalysis, TunerManager
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/autotune/_manager.py", line 22, in <module>
    from scvi.model.base import BaseModelClass
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/model/__init__.py", line 2, in <module>
    from ._amortizedlda import AmortizedLDA
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/model/_amortizedlda.py", line 14, in <module>
    from scvi.module import AmortizedLDAPyroModule
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/__init__.py", line 1, in <module>
    from ._amortizedlda import AmortizedLDAPyroModule
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/_amortizedlda.py", line 14, in <module>
    from scvi.module.base import PyroBaseModuleClass, auto_move_data
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/base/__init__.py", line 1, in <module>
    from ._base_module import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/base/_base_module.py", line 8, in <module>
    import flax
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/__init__.py", line 25, in <module>
    from . import linen
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/__init__.py", line 34, in <module>
    from .activation import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/activation.py", line 21, in <module>
    from flax.linen.module import compact
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/module.py", line 68, in <module>
    from flax.linen import kw_only_dataclasses
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/kw_only_dataclasses.py", line 126, in <module>
    def _process_class(cls: type[M], extra_fields=None, **kwargs):
TypeError: 'type' object is not subscriptable
```
</details>

#### Installation, step 2
From what I read in the repo issues, I tried to best downgrade several modules:
```bash
pip install --upgrade matplotlib==3.3.1 pandas==1.5.3 numpy==1.23.5 scanpy==1.8.0
```
Trying again, I get the same error:
```python
import scvelo
```

### Error
<details>

<summary> Error output </summary>

```pytb
>>> import scvelo
Global seed set to 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/__init__.py", line 6, in <module>
    from scvelo import plotting as pl
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/__init__.py", line 3, in <module>
    from .gridspec import gridspec
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/gridspec.py", line 6, in <module>
    from .scatter import scatter
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/scatter.py", line 16, in <module>
    from .utils import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/plotting/utils.py", line 24, in <module>
    from scvelo.tools.utils import strings_to_categoricals
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/tools/__init__.py", line 14, in <module>
    from ._vi_model import VELOVI
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvelo/tools/_vi_model.py", line 14, in <module>
    from scvi.data import AnnDataManager
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/__init__.py", line 10, in <module>
    from . import autotune, data, model, external, utils
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/autotune/__init__.py", line 1, in <module>
    from ._manager import TuneAnalysis, TunerManager
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/autotune/_manager.py", line 22, in <module>
    from scvi.model.base import BaseModelClass
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/model/__init__.py", line 2, in <module>
    from ._amortizedlda import AmortizedLDA
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/model/_amortizedlda.py", line 14, in <module>
    from scvi.module import AmortizedLDAPyroModule
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/__init__.py", line 1, in <module>
    from ._amortizedlda import AmortizedLDAPyroModule
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/_amortizedlda.py", line 14, in <module>
    from scvi.module.base import PyroBaseModuleClass, auto_move_data
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/base/__init__.py", line 1, in <module>
    from ._base_module import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/scvi/module/base/_base_module.py", line 8, in <module>
    import flax
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/__init__.py", line 25, in <module>
    from . import linen
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/__init__.py", line 34, in <module>
    from .activation import (
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/activation.py", line 21, in <module>
    from flax.linen.module import compact
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/module.py", line 68, in <module>
    from flax.linen import kw_only_dataclasses
  File "/data/p_magnuson_lab/conda/envs/scvelo_py38/lib/python3.8/site-packages/flax/linen/kw_only_dataclasses.py", line 126, in <module>
    def _process_class(cls: type[M], extra_fields=None, **kwargs):
TypeError: 'type' object is not subscriptable
```

</details>

### List of modules

<details>
<summary>pip list</summary>

Package                  Version
------------------------ ------------
absl-py                  1.4.0
aiohttp                  3.8.5
aiosignal                1.3.1
anndata                  0.9.2
async-timeout            4.0.3
attrs                    23.1.0
blosc2                   2.0.0
cached-property          1.5.2
certifi                  2023.7.22
charset-normalizer       3.2.0
chex                     0.1.7
click                    8.1.7
cmake                    3.27.4.1
contextlib2              21.6.0
contourpy                1.1.0
cycler                   0.11.0
Cython                   3.0.2
dm-tree                  0.1.8
docrep                   0.3.2
dunamai                  1.18.0
et-xmlfile               1.1.0
etils                    1.3.0
filelock                 3.12.3
flax                     0.7.3
fonttools                4.42.1
frozenlist               1.4.0
fsspec                   2023.9.0
get_version              3.5.4
h5py                     3.9.0
idna                     3.4
importlib-metadata       6.8.0
importlib-resources      6.0.1
jax                      0.4.13
jaxlib                   0.4.13
Jinja2                   3.1.2
joblib                   1.3.2
kiwisolver               1.4.5
legacy-api-wrap          1.2
lightning-utilities      0.9.0
lit                      16.0.6
llvmlite                 0.40.1
loompy                   3.0.7
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.3.1
mdurl                    0.1.2
ml-collections           0.1.1
ml-dtypes                0.2.0
mpmath                   1.3.0
msgpack                  1.0.5
mudata                   0.2.3
multidict                6.0.4
multipledispatch         1.0.0
natsort                  8.4.0
nest-asyncio             1.5.7
networkx                 3.1
numba                    0.57.1
numexpr                  2.8.6
numpy                    1.23.5
numpy-groupies           0.9.22
numpyro                  0.12.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
openpyxl                 3.1.2
opt-einsum               3.3.0
optax                    0.1.7
orbax-checkpoint         0.2.3
packaging                23.1
pandas                   1.5.3
patsy                    0.5.3
Pillow                   10.0.0
pip                      23.2.1
py-cpuinfo               9.0.0
Pygments                 2.16.1
pynndescent              0.5.10
pyparsing                3.1.1
pyro-api                 0.1.2
pyro-ppl                 1.8.6
python-dateutil          2.8.2
pytorch-lightning        1.9.5
pytz                     2023.3.post1
PyYAML                   6.0.1
requests                 2.31.0
rich                     13.5.2
scanpy                   1.8.0
scikit-learn             1.1.3
scipy                    1.10.1
scvelo                   0.3.0
scvi-tools               0.20.3
seaborn                  0.12.2
session-info             1.0.0
setuptools               68.0.0
sinfo                    0.3.4
six                      1.16.0
statsmodels              0.14.0
stdlib-list              0.9.0
sympy                    1.12
tables                   3.8.0
tensorstore              0.1.42
threadpoolctl            3.2.0
toolz                    0.12.0
torch                    2.0.1
torchmetrics             1.1.2
tqdm                     4.66.1
triton                   2.0.0
typing_extensions        4.7.1
tzdata                   2023.3
umap-learn               0.5.3
urllib3                  2.0.4
wheel                    0.38.4
yarl                     1.9.2
zipp                     3.16.2

</details>

###  scvelo version
```pytb
# paste the ouput of scv.logging.print_versions() here
scvelo-0.3.0.dist-info # can't run  cv.logging.print_versions()  since module doesn't load
```

**Comment by YitengDang** [comment]
I was getting exactly the same problem, but managed to fixed it by updating a library called flax. This is described in detail here:
https://github.com/google/jax/issues/7796

Therefore, I installed the GitHub master of scvelo first, then I updated flax using `pip install --upgrade flax` to flax=0.7.5 and the import error for scvelo disappeared.

**Comment by WeilerP** [comment]
Works fine for me. Please try with latest versions.
