### ISSUE TITLE
Error with matplotlib 3.8.0: unable to import scvelo

### ISSUE THREAD

**Issue by nekonekko** [theislab/scvelo#1124]
scVelo did not work with matplotlib ver. 3.8.0 released on 9/15.

I created a virtual environment with only scvelo in it and tried to import, but the import failed.

```sh
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install scvelo
```

```python
import scvelo
```

<details>

<summary> Error output </summary>

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/__init__.py", line 5, in <module>
    from scvelo import datasets, logging
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/datasets/__init__.py", line 1, in <module>
    from ._datasets import (
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/datasets/_datasets.py", line 10, in <module>
    from scvelo.core import cleanup
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/core/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/core/_anndata.py", line 15, in <module>
    from scvelo import logging as logg
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/logging.py", line 12, in <module>
    from scvelo import settings
  File "/Users/username/myfolder/.venv/lib/python3.11/site-packages/scvelo/settings.py", line 91, in <module>
    warnings.filterwarnings("ignore", category=cbook.mplDeprecation)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'
```

</details>

<details> <summary> Versions </summary>

```pytb
Python==3.11.5
scvelo==0.2.5
matplotlib==3.8.0
```

</details>

**Comment by vasikara17** [comment]
Hello, I am having also a problem with loading the library in python. 
I have also the version 3.8.0
import scvelo as scv

Error Lines:
 warnings.filterwarnings("ignore", category=cbook.mplDeprecation)
AttributeError: module 'matplotlib.cbook' has no attribute **'mplDeprecation'**

**Comment by yamihn** [comment]
yes same for me.

**Comment by nekonekko** [comment]
It is not a radical solution, but downgrading matplotlib to a version lower than 3.8.0 (e.g. 3.7.2) will allow scVelo to work.

**Comment by niehu2018** [comment]
yes same for me.

**Comment by niehu2018** [comment]
> It is not a radical solution, but downgrading matplotlib to a version lower than 3.8.0 (e.g. 3.7.2) will allow scVelo to work.

I tried this.
This will alow me to import scVelo.
However, the scv.tl.recover_dynamics did not work properly

**Comment by ivirshup** [comment]
You can monkey patch matplotlib to get around this:

```python
import matplotlib

class mplDeprecation(UserWarning):
    pass

matplotlib.cbook.mplDeprecation = mplDeprecation

import scvelo
```

**Comment by TobiasHohl** [comment]
> You can monkey patch matplotlib to get around this:
> 
> ```python
> import matplotlib
> 
> class mplDeprecation(UserWarning):
>     pass
> 
> matplotlib.cbook.mplDeprecation = mplDeprecation
> 
> import scvelo as scv
> ```

I tried this. Unfortunately, it doesn't work for me (see error message below). Does anybody have any additional information on how to fix this bug?

<details>

<summary>The code I ran:</summary>

```python
import matplotlib

class mplDeprecation(UserWarning):
    pass

matplotlib.cbook.mplDeprecation = mplDeprecation


import scanpy as sc
import scvelo as scv

# import adata (code not shown)

scv.tl.recover_dynamics(adata, n_jobs=8)
```

</details>

<details>

<summary>Error output:</summary>

```python
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/path/to/anaconda/envs/cellrank2/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/anaconda/envs/cellrank2/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/__init__.py", line 5, in <module>
    from scvelo import datasets, logging
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/datasets/__init__.py", line 1, in <module>
    from ._datasets import (
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/datasets/_datasets.py", line 10, in <module>
    from scvelo.core import cleanup
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/core/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/core/_anndata.py", line 15, in <module>
    from scvelo import logging as logg
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/logging.py", line 12, in <module>
    from scvelo import settings
  File "/path/to/conda/environment/lib/python3.11/site-packages/scvelo/settings.py", line 91, in <module>
    warnings.filterwarnings("ignore", category=cbook.mplDeprecation)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
Cell In[129], line 1
----> 1 scv.tl.recover_dynamics(adata, n_jobs=8)

File /path/to/conda/environment/lib/python3.11/site-packages/scvelo/tools/dynamical_model.py:509, in recover_dynamics(data, var_names, n_top_genes, max_iter, assignment_mode, t_max, fit_time, fit_scaling, fit_steady_states, fit_connected_states, fit_basal_transcription, use_raw, load_pars, return_model, plot_results, steady_state_prior, add_key, copy, n_jobs, backend, **kwargs)
    505     Tau_ = adata.layers["fit_tau_"]
    507 conn = get_connectivities(adata) if fit_connected_states else None
--> 509 res = parallelize(
    510     _fit_recovery,
    511     var_names,
    512     n_jobs,
    513     unit="gene",
    514     as_array=False,
    515     backend=backend,
    516     show_progress_bar=len(var_names) > 9,
    517 )(
    518     adata=adata,
    519     use_raw=use_raw,
    520     load_pars=load_pars,
    521     max_iter=max_iter,
    522     fit_time=fit_time,
    523     fit_steady_states=fit_steady_states,
    524     fit_scaling=fit_scaling,
    525     fit_basal_transcription=fit_basal_transcription,
    526     steady_state_prior=steady_state_prior,
    527     conn=conn,
    528     assignment_mode=assignment_mode,
    529     **kwargs,
    530 )
    531 idx, dms = map(_flatten, zip(*res))
    533 for ix, dm in zip(idx, dms):

File /path/to/conda/environment/lib/python3.11/site-packages/scvelo/core/_parallelize.py:128, in parallelize.<locals>.wrapper(*args, **kwargs)
    125 else:
    126     pbar, queue, thread = None, None, None
--> 128 res = Parallel(n_jobs=n_jobs, backend=backend)(
    129     delayed(callback)(
    130         *((i, cs) if use_ixs else (cs,)),
    131         *args,
    132         **kwargs,
    133         queue=queue,
    134     )
    135     for i, cs in enumerate(collections)
    136 )
    138 res = np.array(res) if as_array else res
    139 if thread is not None:

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:1952, in Parallel.__call__(self, iterable)
   1946 # The first item from the output is blank, but it makes the interpreter
   1947 # progress until it enters the Try/Except block of the generator and
   1948 # reach the first `yield` statement. This starts the aynchronous
   1949 # dispatch of the tasks to the workers.
   1950 next(output)
-> 1952 return output if self.return_generator else list(output)

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:1595, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1592     yield
   1594     with self._backend.retrieval_context():
-> 1595         yield from self._retrieve()
   1597 except GeneratorExit:
   1598     # The generator has been garbage collected before being fully
   1599     # consumed. This aborts the remaining tasks if possible and warn
   1600     # the user if necessary.
   1601     self._exception = True

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:1699, in Parallel._retrieve(self)
   1692 while self._wait_retrieval():
   1693 
   1694     # If the callback thread of a worker has signaled that its task
   1695     # triggered an exception, or if the retrieval loop has raised an
   1696     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1697     # worker traceback.
   1698     if self._aborting:
-> 1699         self._raise_error_fast()
   1700         break
   1702     # If the next job is not ready for retrieval yet, we just wait for
   1703     # async callbacks to progress.

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:1734, in Parallel._raise_error_fast(self)
   1730 # If this error job exists, immediatly raise the error by
   1731 # calling get_result. This job might not exists if abort has been
   1732 # called directly or if the generator is gc'ed.
   1733 if error_job is not None:
-> 1734     error_job.get_result(self.timeout)

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:736, in BatchCompletionCallBack.get_result(self, timeout)
    730 backend = self.parallel._backend
    732 if backend.supports_retrieve_callback:
    733     # We assume that the result has already been retrieved by the
    734     # callback thread, and is stored internally. It's just waiting to
    735     # be returned.
--> 736     return self._return_or_raise()
    738 # For other backends, the main thread needs to run the retrieval step.
    739 try:

File /path/to/conda/environment/lib/python3.11/site-packages/joblib/parallel.py:754, in BatchCompletionCallBack._return_or_raise(self)
    752 try:
    753     if self.status == TASK_ERROR:
--> 754         raise self._result
    755     return self._result
    756 finally:

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

</details>

<details>

<summary>Versions:</summary>

```
Python==3.11.6
scvelo==0.2.5
scanpy==1.9.5
matplotlib-base==3.8.0
```

</details>

**Comment by juanmatavira** [comment]
I have the same issue

**Comment by TobiasHohl** [comment]
Alright - I pieced together a solution that works for me using information from [here](https://github.com/theislab/scvelo/pull/1059#issuecomment-1683538354):

<details>
  <summary>env.yaml</summary>

  ```yaml
  name: myCondaEnv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - cellrank
  - jinja2=3.0.3
  - matplotlib=3.7.2
  - pip:
    - git+https://github.com/theislab/scvelo
  ```

</details>

Install with `mamba create -f env.yaml`.

The important parts I found were `python=3.8`, `jinja2=3.0.3`, and `matplotlib=3.7.2`. So yes, downgrading matplotlib is an option, but downgrading python was what made it work for me for the first time.

**Comment by WeilerP** [comment]
Works with latest versions.

**Comment by nekonekko** [comment]
Thank you for resolving and closing the issue!
