### ISSUE TITLE
Error when using scv.tl.velocity_graph

### ISSUE THREAD

**Issue by KforKuma** [theislab/scvelo#1174]
Quite similar to https://github.com/theislab/scvelo/issues/954
Interestingly in all 4 times I tried, it worked once but failed other times. I still don't know why.

my anndata object is very small so I guess using pancreas could produce same result, I'm gonna try it later (since my server is currently with internet problem)
```python
scv.tl.velocity_graph(matching_velo)
```

<details>

<summary> Error output </summary>

```pytb
computing velocity graph (using 1/24 cores)
  0%|          | 0/8389 [00:00<?, ?cells/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 373, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/site-packages/scvelo/tools/velocity_graph.py", line 185, in compute_cosines
    res = parallelize(
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/site-packages/scvelo/core/_parallelize.py", line 121, in wrapper
    queue = Manager().Queue()
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/managers.py", line 723, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/managers.py", line 606, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/connection.py", line 513, in Client
    answer_challenge(c, authkey)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/connection.py", line 757, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/data/HeLab/miniconda3/envs/scvpy10/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.3.1  scanpy==1.9.6  anndata==0.10.3  loompy==3.0.7  numpy==1.26.2  scipy==1.11.4  matplotlib==3.7.0  sklearn==1.1.3  pandas==2.1.4  
```

</details>

**Comment by WeilerP** [comment]
Looks like a local issue with multithreading to me and similar to #746 as described in #954.
