### ISSUE TITLE
Recover_dynamics() seems to not work on AnnCollections

### ISSUE THREAD

**Issue by jwalewski** [theislab/scvelo#1191]
Calling recover_dynamics() on an AnnCollection fails as these objects do not have layers. Is there a workaround, or should the stochastic model be used instead?

In theory this should apply to all AnnCollections

<details>

<summary> Error output </summary>

```pytb
Traceback (most recent call last):
  File "<string>", line 361, in <module>
  File "<string>", line 354, in main
  File "<string>", line 317, in recover_and_velocity
  File "/home/jw2894/.local/lib/python3.10/site-packages/scvelo/tools/dynamical_model.py", line 454, in recover_dynamics
    if "Ms" not in adata.layers.keys() or "Mu" not in adata.layers.keys():
AttributeError: 'AnnCollection' object has no attribute 'layers'```

</details>

<!-- Versions -->
<details> <summary> Versions </summary>

```pytb
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```

</details>

**Comment by WeilerP** [comment]
According to the stack trace, the attribute "layers" is missing, _i.e._, there unspliced/spliced counts do not exist; the stochastic model will not work in this case either.
