### ISSUE TITLE
Plotting error at the end of tutorial

### ISSUE THREAD

**Issue by iaconogi** [theislab/scvelo#133]
Dear Volker
I am following the tutorial using the dentate gyrus data. 
When at the end I run the plotting I encounter this error:

scv.pl.velocity_embedding(adata, basis='umap',save='scvelo.pdf')

saving figure to file ./figures/scvelo_scvelo.pdf
Traceback (most recent call last):
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 433, in show
    manager = getattr(self.canvas, 'manager')
AttributeError: 'FigureCanvasPdf' object has no attribute 'manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding.py", line 145, in velocity_embedding
    savefig_or_show(dpi=dpi, save=save, show=show)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/utils.py", line 451, in savefig_or_show
    if show: pl.show()
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 269, in show
    return _show(*args, **kw)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 413, in wrapper
    return func(*args, **kwargs)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3284, in show
    manager.canvas.figure.show()
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 438, in show
    "created by pyplot.figure()." % err)
AttributeError: 'FigureCanvasPdf' object has no attribute 'manager'
Figure.show works only for figures managed by pyplot, normally created by pyplot.figure().

**Comment by VolkerBergen** [comment]
Thanks, will have a look. In the meanwhile, can you already send me your dependencies?
`scv.logging.print_versions()`

**Comment by VolkerBergen** [comment]
Can I conclude that https://github.com/theislab/scvelo/issues/126 is resolved?

**Comment by iaconogi** [comment]
Yes I think so.

**Comment by iaconogi** [comment]
scvelo==0.1.25.dev44+gf6280eb  scanpy==1.4.4.post1  anndata==0.6.22.post1  loompy==3.0.6  numpy==1.17.2  scipy==1.3.1  matplotlib==3.1.1  sklearn==0.21.3  pandas==0.25.1

**Comment by VolkerBergen** [comment]
Couldn't reproduce that error. There has been recently some issues with matplotlib though. Can you try rerunning with matplotlib downgraded to 
`pip install matplotlib==3.0.3`.

**Comment by iaconogi** [comment]
I can close the issue. The error message remains but I realized the plot is actually created and looks okay.
