### ISSUE TITLE
Install failed: an EnvironmentError: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by grimwoo** [theislab/scvelo#135]
Hi, I tried all the code in this [website ](https://scvelo.readthedocs.io/getting_started.html) but it often gives this result:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/networkx-2.3.dist-info/METADATA'
```

And this is the code I used:

**Comment by grimwoo** [comment]
Total infomation:

#1
```
(Grim3.6.8) [wuhaoda@ln02 scvelo-master]$ pip install git+git://github.com/theislab/scvelo.git
Collecting git+git://github.com/theislab/scvelo.git
  Cloning git://github.com/theislab/scvelo.git to /tmp/pip-req-build-vplurhf7
  Running command git clone -q git://github.com/theislab/scvelo.git /tmp/pip-req-build-vplurhf7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: loompy>=2.0.12 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (3.0.6)
Requirement already satisfied: pandas>=0.23 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.25.3)
Requirement already satisfied: scikit-learn>=0.21.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.22)
Requirement already satisfied: scipy>=1.0 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.3.3)
Requirement already satisfied: matplotlib>=2.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (3.0.3)
Requirement already satisfied: scanpy>=1.4 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.4.4.post1)
Requirement already satisfied: umap-learn>=0.3 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.3.10)
Requirement already satisfied: anndata>=0.6.21 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.6.22.post1)
Requirement already satisfied: numpy>=1.17 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.17.4)
Requirement already satisfied: numpy-groupies in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (0+unknown)
Requirement already satisfied: h5py in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (2.10.0)
Requirement already satisfied: numba in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (0.46.0)
Requirement already satisfied: setuptools in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (41.0.1)
Requirement already satisfied: click in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (7.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from pandas>=0.23->scvelo==0.1.25.dev55+gb890ea3) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from pandas>=0.23->scvelo==0.1.25.dev55+gb890ea3) (2019.3)
Requirement already satisfied: joblib>=0.11 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scikit-learn>=0.21.2->scvelo==0.1.25.dev55+gb890ea3) (0.14.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo==0.1.25.dev55+gb890ea3) (2.4.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo==0.1.25.dev55+gb890ea3) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo==0.1.25.dev55+gb890ea3) (0.10.0)
Requirement already satisfied: tables in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (3.6.1)
Requirement already satisfied: seaborn in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (0.9.0)
Requirement already satisfied: statsmodels>=0.10.0rc2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (0.10.2)
Requirement already satisfied: patsy in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (0.5.1)
Requirement already satisfied: networkx in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (2.3)
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/networkx-2.3.dist-info/METADATA'
```

#2
```
(Grim3.6.8) [wuhaoda@ln02 scvelo-master]$ pip install git+git://github.com/theislab/scvelo
Collecting git+git://github.com/theislab/scvelo
  Cloning git://github.com/theislab/scvelo to /tmp/pip-req-build-uws5gqyu
  Running command git clone -q git://github.com/theislab/scvelo /tmp/pip-req-build-uws5gqyu
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: loompy>=2.0.12 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (3.0.6)
Requirement already satisfied: scanpy>=1.4 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.4.4.post1)
Requirement already satisfied: anndata>=0.6.21 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.6.22.post1)
Requirement already satisfied: umap-learn>=0.3 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.3.10)
Requirement already satisfied: scipy>=1.0 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.3.3)
Requirement already satisfied: matplotlib>=2.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (3.0.3)
Requirement already satisfied: pandas>=0.23 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.25.3)
Requirement already satisfied: scikit-learn>=0.21.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (0.22)
Requirement already satisfied: numpy>=1.17 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo==0.1.25.dev55+gb890ea3) (1.17.4)
Requirement already satisfied: numba in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (0.46.0)
Requirement already satisfied: setuptools in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (41.0.1)
Requirement already satisfied: numpy-groupies in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (0+unknown)
Requirement already satisfied: click in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (7.0)
Requirement already satisfied: h5py in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo==0.1.25.dev55+gb890ea3) (2.10.0)
Requirement already satisfied: natsort in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (6.2.0)
Requirement already satisfied: tables in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (3.6.1)
Requirement already satisfied: networkx in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo==0.1.25.dev55+gb890ea3) (2.3)
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/networkx-2.3.dist-info/METADATA'
```

#3
```
(Grim3.6.8) [wuhaoda@ln02 scvelo-master]$ pip install -U scvelo
Collecting scvelo
  Using cached https://files.pythonhosted.org/packages/62/da/0b40b56a7a7c2b01fb3d978b7225c3f33558092a8c7a8374d67285f04c4b/scvelo-0.1.24-py3-none-any.whl
Requirement already satisfied, skipping upgrade: scikit-learn>=0.21.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (0.22)
Requirement already satisfied, skipping upgrade: pandas>=0.23 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (0.25.3)
Requirement already satisfied, skipping upgrade: loompy>=2.0.12 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (3.0.6)
Requirement already satisfied, skipping upgrade: matplotlib>=2.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (3.0.3)
Requirement already satisfied, skipping upgrade: scipy>=1.0 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (1.3.3)
Requirement already satisfied, skipping upgrade: numpy>=1.17 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (1.17.4)
Requirement already satisfied, skipping upgrade: umap-learn>=0.3 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (0.3.10)
Requirement already satisfied, skipping upgrade: anndata>=0.6.18 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (0.6.22.post1)
Requirement already satisfied, skipping upgrade: scanpy>=1.4 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scvelo) (1.4.4.post1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scikit-learn>=0.21.2->scvelo) (0.14.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from pandas>=0.23->scvelo) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from pandas>=0.23->scvelo) (2.8.1)
Requirement already satisfied, skipping upgrade: h5py in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo) (2.10.0)
Requirement already satisfied, skipping upgrade: numpy-groupies in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo) (0+unknown)
Requirement already satisfied, skipping upgrade: click in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo) (7.0)
Requirement already satisfied, skipping upgrade: setuptools in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo) (41.0.1)
Requirement already satisfied, skipping upgrade: numba in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from loompy>=2.0.12->scvelo) (0.46.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo) (1.1.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from matplotlib>=2.2->scvelo) (2.4.5)
Requirement already satisfied, skipping upgrade: natsort in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from anndata>=0.6.18->scvelo) (6.2.0)
Requirement already satisfied, skipping upgrade: patsy in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo) (0.5.1)
Requirement already satisfied, skipping upgrade: statsmodels>=0.10.0rc2 in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo) (0.10.2)
Requirement already satisfied, skipping upgrade: tqdm in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo) (4.40.0)
Requirement already satisfied, skipping upgrade: seaborn in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo) (0.9.0)
Requirement already satisfied, skipping upgrade: networkx in /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages (from scanpy>=1.4->scvelo) (2.3)
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/networkx-2.3.dist-info/METADATA'
```

**Comment by grimwoo** [comment]
Then I tried to unpack the zip.file from github and install it directly, but it gave the following information:
```
(Grim3.6.8) [wuhaoda@ln02 scvelo-master]$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'Topic :: Scientific/Engineering :: Visualization']
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/setuptools/dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/setuptools/dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/integration.py", line 17, in version_keyword
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 150, in get_version
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 113, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
(Grim3.6.8) [wuhaoda@ln02 scvelo-master]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'Topic :: Scientific/Engineering :: Visualization']
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/setuptools/dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/setuptools/dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/integration.py", line 17, in version_keyword
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 150, in get_version
  File "/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 113, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/public-supool/home/wuhaoda/R_Jupyter/Packages_downloaded/scvelo-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by VolkerBergen** [comment]
Seems to be an issue with networkx.
Try (re)installing https://networkx.github.io/documentation/stable/install.html

**Comment by grimwoo** [comment]
@VolkerBergen Thanks for your early reply, and it really works!!
