### ISSUE TITLE
Error when plotting the final result

### ISSUE THREAD

**Issue by iaconogi** [theislab/scvelo#136]
Dear Volker
I am analyzing a dataset transferred from R following the guidelines of another user (here: https://github.com/theislab/anndata/issues/190).
The whole workflow goes without problem, but I receive an error when trying to create the plot.

>>> scv.pp.filter_and_normalize(sdata)
Logarithmized X.
>>> scv.pp.moments(sdata)
computing moments based on connectivities
    finished (0:00:07) --> added
    'Ms' and 'Mu', moments of spliced/unspliced abundances (adata.layers)
>>> scv.tl.velocity(sdata, mode='stochastic')
computing velocities
    finished (0:00:32) --> added
    'velocity', velocity vectors for each individual cell (adata.layers)
>>> scv.tl.velocity_graph(sdata)
computing velocity graph
    finished (0:01:58) --> added
    'velocity_graph', sparse matrix with cosine correlations (adata.uns)
>>> sdata
AnnData object with n_obs × n_vars = 5649 × 31053
    obs: 'fake', 'clusters', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size', 'n_counts', 'velocity_self_transition'
    var: 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'pca', 'neighbors', 'velocity_settings', 'velocity_graph', 'velocity_graph_neg', 'clusters_colors'
    obsm: 'X_umap', 'X_pca', 'velocity_umap', 'velocity_pca'
    varm: 'PCs'
    layers: 'spliced', 'unspliced', 'ambiguous', 'Ms', 'Mu', 'velocity', 'variance_velocity'
>>> scv.pl.velocity_embedding(sdata,save='scvelo.pdf')
computing velocity embedding
    finished (0:00:02) --> added
    'velocity_umap', embedded velocity vectors (adata.obsm)
Traceback (most recent call last):
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1180, in _get_values
    self._data.get_slice(indexer), fastpath=True
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1546, in get_slice
    self._block._slice(slobj), self.index[slobj], fastpath=True
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 317, in _slice
    return self.values[slicer]
IndexError: index 7 is out of bounds for axis 0 with size 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding.py", line 143, in velocity_embedding
    zorder=0, **scatter_kwargs)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py", line 135, in scatter
    legend_fontsize, [patheffects.withStroke(linewidth=True, foreground='w')], groups, False)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/utils.py", line 346, in _add_legend
    valid_cats = adata.obs[value_to_plot].value_counts()[categories] > 0
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1110, in __getitem__
    return self._get_with(key)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1145, in _get_with
    return self._get_values(key)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1183, in _get_values
    return self._values[indexer]
IndexError: index 7 is out of bounds for axis 0 with size 7

I have the same error with both embeddings umap or pca.
If it helps I can send you the file with sdata
Best
Giovanni

**Comment by VolkerBergen** [comment]
If I remember correctly, there has been a bug been resolved in one of the recent commits. Try again with the source version `pip install git+https://github.com/theislab/scvelo`. The next release with some bugfixes is coming out soon.

**Comment by iaconogi** [comment]
Dear Volker,
I have the same problem using the latest version.
Should I send you the object so you can check where the problem is?

scvelo==0.1.25.dev55+gb890ea3  scanpy==1.4.4.post1  anndata==0.6.22.post1  loompy==3.0.6  numpy==1.17.2  scipy==1.3.1  matplotlib==3.0.3  sklearn==0.21.3  pandas==0.25.1  >>> User defined signal 1
>>> scv.pl.velocity_embedding(sdata,save='scvelo.pdf')
computing velocity embedding
    finished (0:00:01) --> added
    'velocity_umap', embedded velocity vectors (adata.obsm)
Traceback (most recent call last):
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1180, in _get_values
    self._data.get_slice(indexer), fastpath=True
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1546, in get_slice
    self._block._slice(slobj), self.index[slobj], fastpath=True
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 317, in _slice
    return self.values[slicer]
IndexError: index 7 is out of bounds for axis 0 with size 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding.py", line 143, in velocity_embedding
    zorder=0, **scatter_kwargs)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py", line 195, in scatter
    [patheffects.withStroke(linewidth=True, foreground='w')], groups)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/scvelo/plotting/utils.py", line 241, in _add_legend
    valid_cats = np.where(obs_vals.value_counts()[obs_vals.cat.categories] > 0)[0]
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1110, in __getitem__
    return self._get_with(key)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1145, in _get_with
    return self._get_values(key)
  File "/scratch/devel/giacono/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1183, in _get_values
    return self._values[indexer]
IndexError: index 7 is out of bounds for axis 0 with size 7

**Comment by VolkerBergen** [comment]
Let's see what you get with
`print(adata.obs['clusters'].cat.categories, adata.obs['clusters'].value_counts())` first.

**Comment by iaconogi** [comment]
Here:
>>> print(sdata.obs['clusters'].cat.categories, sdata.obs['clusters'].value_counts())
Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64') 2    1908
1    1112
4     825
7     777
6     464
3     461
5     102
Name: clusters, dtype: int64

**Comment by VolkerBergen** [comment]
Should be fixed now. Would appreciate to get your feedback. Issue was that louvain is stored as int and in your case unexpectedly starts counting from 1 and not from 0.

**Comment by vasikara17** [comment]
Hello,
I am sorry to open it up again but I have the same issue:
**IndexError: index 12322 is out of bounds for axis 0 with size 2777**
Index(['Epithelial', 'SMCs', 'Adipocyte_1', 'Adipocyte_2', 'Adipocyte_4',
       'Adipocyte_5', 'SMCs_2', 'Epithelial_2', 'Endothelial', 'Macrophages',
       'Neurons', 'Preadipocytes', 'Fibroblasts'],
      dtype='object') seurat_clusters
Adipocyte_1      1082
Endothelial       328
Fibroblasts       271
Preadipocytes     268
Epithelial        232
Macrophages       211
Adipocyte_4       102
Adipocyte_2        91
Epithelial_2       77
Neurons            39
SMCs               30
SMCs_2             29
Adipocyte_5        17
Name: count, dtype: int64
Is there any update on that?
