### ISSUE TITLE
Errors for scv.tl.rank_velocity_genes

### ISSUE THREAD

**Issue by JiangyanYu** [theislab/scvelo#148]
Hi,

Thanks for the tool!  Currently, I am not able to compute velocity clusters with the scvelo version 0.1.25 in python 3.7.4. When I run 
`scv.tl.rank_velocity_genes(adata,match_with='clusters',resolution=.4)`

I got following errors:
`File "<ipython-input-13-799a68fd1114>", line 1, in <module>
    scv.tl.rank_velocity_genes(adata)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\rank_velocity_genes.py", line 224, in rank_velocity_genes
    velocity_clusters(adata, vkey=vkey, match_with=match_with, resolution=resolution, min_likelihood=min_likelihood)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\rank_velocity_genes.py", line 135, in velocity_clusters
    sc.tl.louvain(vdata, resolution=resolution)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scanpy\tools\_louvain.py", line 193, in louvain
    categories=natsorted(np.unique(groups).astype('U')),

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\pandas\core\arrays\categorical.py", line 385, in __init__
    codes = _get_codes_for_values(values, dtype.categories)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\pandas\core\arrays\categorical.py", line 2576, in _get_codes_for_values
    t.map_locations(cats)

  File "pandas\_libs\hashtable_class_helper.pxi", line 1403, in pandas._libs.hashtable.StringHashTable.map_locations

TypeError: Expected unicode, got numpy.str_`

Thanks!

**Comment by VolkerBergen** [comment]
Hi @JiangyanYu, looks like an older version of scanpy.
Could you please let me know the version number `scv.logging.print_versions()` and try again with updating scanpy `pip install -U scanpy`.

**Comment by JiangyanYu** [comment]
I've checked the versions for scvelo and scanpy (see below). However, `pip install -U scanpy` did not solve the problem.

`scv.logging.print_version()`
Running scvelo 0.1.25 (python 3.7.4)
`sc.logging.print_versions()`
scanpy==1.4.5.post3 anndata==0.7.1 umap==0.3.10 numpy==1.17.5 scipy==1.4.1 pandas==1.0.0 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.7.1+5.3b99dbf6 louvain==0.6.1

**Comment by VolkerBergen** [comment]
Can you again send me your error message? That should look different now with updated scanpy.

**Comment by JiangyanYu** [comment]
Sorry, i forgot to post the error information last time. Here is it:

`scv.tl.rank_velocity_genes(adata,resolution=.4)`
computing velocity clusters
Traceback (most recent call last):

  File "<ipython-input-2-7837c6f2d0c0>", line 1, in <module>
    scv.tl.rank_velocity_genes(adata,resolution=.4)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\rank_velocity_genes.py", line 224, in rank_velocity_genes
    velocity_clusters(adata, vkey=vkey, match_with=match_with, resolution=resolution, min_likelihood=min_likelihood)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\rank_velocity_genes.py", line 135, in velocity_clusters
    sc.tl.louvain(vdata, resolution=resolution)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\scanpy\tools\_louvain.py", line 193, in louvain
    categories=natsorted(np.unique(groups).astype('U')),

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\pandas\core\arrays\categorical.py", line 385, in __init__
    codes = _get_codes_for_values(values, dtype.categories)

  File "D:\Users\yu.j\AppData\Local\Continuum\anaconda3\envs\scvelo\lib\site-packages\pandas\core\arrays\categorical.py", line 2576, in _get_codes_for_values
    t.map_locations(cats)

  File "pandas\_libs\hashtable_class_helper.pxi", line 1403, in pandas._libs.hashtable.StringHashTable.map_locations

TypeError: Expected unicode, got numpy.str_

**Comment by ElieElHachem** [comment]
Hi,
I had excatly the same problem. It seems that the issue come from the fact that numpy.str_ is not considered as an unicode.
The solution that I'm going to give you is just for this type of errors : TypeError: Expected unicode, got numpy.str_
Assuming that you have this error in rank_velocity_genes.py file :

```
   values=groups.astype('U'),
        categories=natsorted(np.unique(groups).astype('U')),
```

You just have to remove `.astype('U') ` from the code, and this will give you
```
 values=groups.astype('U'),
        categories=natsorted(np.unique(groups).astype('U')),
```

This should fix your problem.

**Comment by VolkerBergen** [comment]
That'd be
```
values=groups.astype('U'),
categories=natsorted(map(str, np.unique(groups)))
```
which has been resolved with the latest scanpy commit https://github.com/theislab/scanpy/pull/1015, to be installed from source via `pip install git+https://github.com/theislab/scanpy`.

**Comment by VolkerBergen** [comment]
This is resolved now with scanpy's latest release
https://github.com/theislab/scanpy/releases/tag/1.4.5.1.
