### ISSUE TITLE
"retain_genes" parameter mentioned in the docs is not found for scv.pp.filter_and_normalize

### ISSUE THREAD

**Issue by jmchan88** [theislab/scvelo#225]
...
Hello! I tried using the "retain_genes" parameter in scv.pp.filter_and_normalize as described in the docs, but it is not found in the function. I believe I am using the most recent version 0.2.1.

```python
scv.pp.filter_and_normalize(scvelo_adata, min_counts=20, min_counts_u=10, n_top_genes = n_top_genes, retain_genes = retain_genes)
```

I get the error below:

/home/chanj3/anaconda3/lib/python3.7/site-packages/dask/config.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/home/chanj3/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Traceback (most recent call last):
  File "/home/chanj3/scripts/SCPC_transformation.021120/run_scvelo.wt.retain_genes.py", line 110, in <module>
    scv.pp.filter_and_normalize(scvelo_adata, min_counts=20, min_counts_u=10, n_top_genes = n_top_genes, retain_genes = retain_genes)
  File "/home/chanj3/anaconda3/lib/python3.7/site-packages/scvelo/preprocessing/utils.py", line 656, in filter_and_normalize
    normalize_per_cell(adata, layers=layers_normalize, **kwargs)
TypeError: normalize_per_cell() got an unexpected keyword argument 'retain_genes'

**Comment by jmchan88** [comment]
Ah apologies, I see that that's a feature of the development version 0.2.2!
