### ISSUE TITLE
Installation with conda require higher version of anndata

### ISSUE THREAD

**Issue by lldelisle** [theislab/scvelo#254]
Hi,
I just to report a bug that I solved:
At first, I installed with conda:
```bash
conda create  -c bioconda -c conda-forge -n scVeloPy3.7 python=3.7 scvelo
conda activate scVeloPy3.7
```

```python
>>> import scvelo as scv            
/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
>>> adata = scv.read("mouseBM.h5ad")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/scanpy/readwrite.py", line 97, in read
    backup_url=backup_url, cache=cache, **kwargs,
  File "/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/scanpy/readwrite.py", line 499, in _read
    return read_h5ad(filename, backed=backed)
  File "/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/anndata/readwrite/read.py", line 502, in _read_args_from_h5ad
    return AnnData._args_from_dict(d)
  File "/slipstream/galaxy/production/dependencies/_conda/envs/scVeloPy3.7/lib/python3.7/site-packages/anndata/core/anndata.py", line 2157, in _args_from_dict
    if key in d_true_keys[true_key].dtype.names:
AttributeError: 'dict' object has no attribute 'dtype'
```

#### Version:
```
(scVeloPy3.7) $ conda list | grep scvelo
scvelo                    0.2.1                      py_0    bioconda

```

To solve the issue, I did:
`conda install -c bioconda -c conda-forge "annData>=0.7"`

Then
```
>>> import scvelo as scv
>>> adata = scv.read("mouseBM.h5ad")
>>> quit()
```

I think it would be good to update the bioconda recipe...

Thanks

**Comment by VolkerBergen** [comment]
Thanks for raising this! Wasn't even aware there is conda version of scvelo. @flying-sheep have you pushed it to conda? If so, could you please update?

**Comment by flying-sheep** [comment]
For the question who committed it, just check this please: https://github.com/bioconda/bioconda-recipes/commits/master/recipes/scvelo/meta.yaml

**Comment by lldelisle** [comment]
Thanks
