### ISSUE TITLE
Cannot import scvelo

### ISSUE THREAD

**Issue by saeedfc** [theislab/scvelo#278]
scevlo has been working fine for me until I updated anndata, scanpy and scvelo. Now when I load scvelo it throws an error.

`import scvelo as scv`

```Traceback (most recent call last):

  File "<ipython-input-2-201be3717d36>", line 1, in <module>
    import scvelo as scv

  File "/home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages/scvelo/__init__.py", line 16, in <module>
    from .read_load import AnnData, read, read_loom, load, read_csv, get_df, DataFrame

  File "/home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages/scvelo/read_load.py", line 12, in <module>
    from scanpy import read, read_loom

  File "/home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages/scanpy/__init__.py", line 41, in <module>
    from anndata import AnnData, concat

ImportError: cannot import name 'concat' from 'anndata' (/home/luna.kuleuven.be/u0119129/anaconda3/lib/python3.7/site-packages/anndata/__init__.py)
```

I tried with anndata version anndata==0.7.1 instead of anndata==0.7.4(or anndata==0.7.3)(version before concatenate update). Still throws the same error. I am using scvelo==0.2.2.
Kindly help out!
 </summary>

</details>

#### Versions:

>

**Comment by saeedfc** [comment]
Hi,

I unistalled anndata and reinstalled scvelo. Working fine now.

Thanks
