### ISSUE TITLE
installation and import error

### ISSUE THREAD

**Issue by wfma** [theislab/scvelo#301]
Hello! I followed the instruction on the scVelo site and when I tried to import scvelo as followed I get an error message:

```
import scvelo as scv
/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/anndata/base.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):

  File "<ipython-input-1-201be3717d36>", line 1, in <module>
    import scvelo as scv

  File "/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/scvelo/__init__.py", line 16, in <module>
    from .read_load import AnnData, read, read_loom, load, read_csv, get_df, DataFrame

  File "/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/scvelo/read_load.py", line 1, in <module>
    from . import logging as logg

  File "/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/scvelo/logging.py", line 9, in <module>
    from anndata.logging import get_memory_usage

  File "/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData

  File "/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/anndata/base.py", line 21, in <module>
    from scipy.sparse.sputils import IndexMixin

ImportError: cannot import name 'IndexMixin' from 'scipy.sparse.sputils' (/Users/wm5wt/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/sputils.py)
```
I have the latest packages installed as followed:
```
pip install --user -U numpy scipy matplotlib ipython jupyter pandas sympy nose
pip install -U scvelo
pip install -U anndata
pip install -U scanpy
pip install -U leidenalg
```
So sorry if its an obvious issue, I am new to python.
Thanks,
Wei

**Comment by wfma** [comment]
actually looks like i resolved the issue by restarting everything after running the upgrade commands! yay
