### ISSUE TITLE
tl.recover_dynamics give `TypeError: unhashable type: 'list'`

### ISSUE THREAD

**Issue by rfenouil** [theislab/scvelo#306]
Hello, and thank you for the great package.

I started using scVelo earlier this year and have been able to reproduce most of the steps described in the tutorials.
Recently, as I could not manage to generate graphs of gene expression VS latent time as in [here](https://scvelo.readthedocs.io/DynamicalModeling.html#Top-likelihood-genes), I decided to try updating my scVelo version (0.2.1) to something newer.

However, since this update (I tried 0.2.2 and latest dev from git -> 0.2.3) the call to `tl.recover_dynamics` function fails with an error message (see below).

Here is the minimal code that used to work and now generates an error:
```python

import scvelo as scv

scv.logging.print_version()
scv.logging.print_versions()

adata = scv.datasets.pancreas()

scv.pp.filter_and_normalize(adata, min_shared_counts=20, min_shared_cells=20, n_top_genes=5000)
scv.pp.neighbors(adata)
scv.pp.moments(adata, n_pcs=30, n_neighbors=10)


scv.tl.recover_dynamics(adata)
```

I then tried to come back to version 0.2.1 but the error remains.... So I bellieve something else is wrong on my system...
Because I'm using docker I can still execute the code on the "working" version and the "non-wokring" one.
Python version is 3.7.3 on both but with different release date... Could this be an issue ?

Please find below execution of the same code on both containers:

<details>
<summary> Non-working container </summary>

```python

root@822509df64a4:/# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scvelo as scv
>>> 
>>> scv.logging.print_version()
Running scvelo 0.2.1 (python 3.7.3) on 2020-11-06 14:52.
>>> scv.logging.print_versions()
scvelo==0.2.1  scanpy==1.6.0  anndata==0.7.4  loompy==3.0.6  numpy==1.19.4  scipy==1.5.4  matplotlib==3.3.2  sklearn==0.23.2  pandas==1.1.4  >>> 
>>> adata = scv.datasets.pancreas()
endocrinogenesis_day15.h5ad: 52.5MB [00:04, 11.7MB/s]                                                                                                                                                                          
>>> 
>>> scv.pp.filter_and_normalize(adata, min_shared_counts=20, min_shared_cells=20, n_top_genes=5000)
Filtered out 22533 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Logarithmized X.
>>> scv.pp.neighbors(adata)
computing neighbors
    finished (0:00:02) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
>>> scv.pp.moments(adata, n_pcs=30, n_neighbors=10)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of spliced/unspliced abundances (adata.layers)
>>> 
>>> 
>>> scv.tl.recover_dynamics(adata)
recovering dynamics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scvelo/tools/dynamical_model.py", line 342, in recover_dynamics
    var_names = np.array([name for name in make_unique_list(var_names, allow_array=True) if name in adata.var_names])
  File "/usr/local/lib/python3.7/dist-packages/scvelo/tools/dynamical_model.py", line 342, in <listcomp>
    var_names = np.array([name for name in make_unique_list(var_names, allow_array=True) if name in adata.var_names])
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 4071, in __contains__
    hash(key)
TypeError: unhashable type: 'list'
>>> 
```

</details>

<details>
<summary> Working container </summary>

```python

root@6a82a6cdc827:/# python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scvelo as scv
>>> 
>>> scv.logging.print_version()
Running scvelo 0.2.1 (python 3.7.3) on 2020-11-06 14:52.
>>> scv.logging.print_versions()
scvelo==0.2.1  scanpy==1.5.1  anndata==0.7.4  loompy==3.0.6  numpy==1.19.0  scipy==1.5.1  matplotlib==3.2.2  sklearn==0.23.1  pandas==1.0.5  >>> 
>>> adata = scv.datasets.pancreas()
endocrinogenesis_day15.h5ad: 52.5MB [00:05, 9.93MB/s]                                                                                                                                                                          
>>> 
>>> scv.pp.filter_and_normalize(adata, min_shared_counts=20, min_shared_cells=20, n_top_genes=5000)
Filtered out 22533 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Logarithmized X.
>>> scv.pp.neighbors(adata)
computing neighbors
    finished (0:00:02) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
>>> scv.pp.moments(adata, n_pcs=30, n_neighbors=10)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of spliced/unspliced abundances (adata.layers)
>>> 
>>> 
>>> scv.tl.recover_dynamics(adata)
recovering dynamics
... 61%
```

</details>

Thank you for you help.

Update: 
I also tried to build a docker image like the "non-working" one, but specifying manually the versions of dependencies (in case it comes from one of them). That did not help

```python
>>> scv.logging.print_versions()
scvelo==0.2.1  scanpy==1.5.1  anndata==0.7.4  loompy==3.0.6  numpy==1.19.0  scipy==1.5.1  matplotlib==3.2.2  sklearn==0.23.2  pandas==1.0.5
...

# scv.tl.recover_dynamics(adata) # fails
```

**Comment by chatterjee89** [comment]
I have the same error. Following.

**Comment by linxy29** [comment]
Have the same error too. Following.

**Comment by iumpeius** [comment]
Here is what worked for me. My error resulted from the fact that my string data were read as bytes, which was done by h5py (version >= 3.0). But anndata (version 0.7.5) now is compatible with the more recent versions of h5py and, by upgrading anndata, the problem faded away like the morning dew.

**Comment by nhuhoa** [comment]
Dear all, 
I also have the same issue, and the bug is at byte type instead of string type format.  And resolve this issue by re-install anndata following the suggestion from iumpeius. I use anndata version 0.7.5, h5py (version >= 3.0). Thanks iumpeius.

**Comment by lashoun** [comment]
In my case, the problem persisted with both anndata 0.7.5 and h5py 3.1.0, but downgrading h5py to 2.10.0 solved it.

**Comment by WeilerP** [comment]
Thanks for resolving the issue @iumpeius!
