### ISSUE TITLE
TypeError in filter_and_normalize

### ISSUE THREAD

**Issue by somnathtagore** [theislab/scvelo#346]
Hi ScVelo Team,

I am trying to combine multiple samples (loom files) using the loompy.combine method. This is working fine.  But, when  I try to do

scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

I am getting this error:

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe' 

I believe this is some error due to datatypes, but I am not sure why i get this in this respect. Also, scvelo runs fine on individual loom files.

**Comment by WeilerP** [comment]
Could you please provide the full stack trace? Also, which versions are you currently running? For the latter you can simply run `scv.logging.print_versions()`.
Right now my guess would be that the issue is either related to [this](scv.logging.print_versions()) fixed Scanpy issue or [this](https://github.com/theislab/scvelo/blob/f1ed31fe85719923563456b1dce8b3a19b98b446/scvelo/preprocessing/utils.py#L718) line of code.

**Comment by somnathtagore** [comment]
Hi,
The details are:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Abundance of ['spliced', 'unspliced']: [0.31 0.69]
AnnData object with n_obs × n_vars = 65795 × 60675
    layers: 'spliced', 'unspliced'

Exception:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 48, in run
    pypi_hits = self.search(query, options)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 65, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/home/ubuntu/anaconda3/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/home/ubuntu/anaconda3/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pip/_internal/download.py", line 826, in request
    return self.parse_response(response.raw)
  File "/home/ubuntu/anaconda3/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/home/ubuntu/anaconda3/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
None
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Filtered out 42145 genes that are detected 20 counts (spliced).
Filtered out 2928 genes that are detected 10 counts (unspliced).
Normalized count data: X, spliced, unspliced.
Traceback (most recent call last):
  File "scvelo.run.cell.anno.L01cov.to.L22cov.py", line 94, in <module>
    scv.pp.filter_and_normalize(adata_sel, min_counts=20, min_counts_u=10, n_top_genes=10000)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/scvelo/preprocessing/utils.py", line 821, in filter_and_normalize
    adata, n_top_genes=n_top_genes, retain_genes=retain_genes, flavor=flavor
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/scvelo/preprocessing/utils.py", line 488, in filter_genes_dispersion
    disp_std_bin[one_gene_per_bin] = disp_mean_bin[one_gene_per_bin].values
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 905, in __getitem__
    if is_iterator(key):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/inference.py", line 157, in is_iterator
    return hasattr(obj, '__next__')
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5065, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3985, in _can_hold_identifiers_and_holds_name
    return name in self
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/category.py", line 327, in __contains__
    return contains(self, key, container=self._engine)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 188, in contains
    loc = cat.categories.get_loc(key)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 770, in get_loc
    start, stop = self._find_non_overlapping_monotonic_bounds(key)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 717, in _find_non_overlapping_monotonic_bounds
    start = self._searchsorted_monotonic(key, 'left')
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 681, in _searchsorted_monotonic
    return sub_idx._searchsorted_monotonic(label, side)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4756, in _searchsorted_monotonic
    return self.searchsorted(label, side=side)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas/core/base.py", line 1501, in searchsorted
    return self._values.searchsorted(value, side=side, sorter=sorter)
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

The versions are:
scvelo==0.2.2  scanpy==1.7.0rc1  anndata==0.7.5  loompy==3.0.6  numpy==1.19.5  scipy==1.6.0  matplotlib==3.3.3  sklearn==0.24.0  pandas==0.24.2

**Comment by WeilerP** [comment]
* You seem to be using conflicting dependencies: `anndata==0.7.5` depends on `pandas>=1.0, !=1.1`. Does the error persist when updating the version of `pandas`?

* If the error is still thrown, what is the data type of `adata.X`, `adata.layers["unspliced"]` and `adata.layers["spliced"]` prior to passing it to `filter_and_normalize`?

**Comment by somnathtagore** [comment]
I tried updated panda using: 

conda update pandas

The following packages were REMOVED:

  backports.os-0.1.1-py37_0
  pytest-arraydiff-0.3-py37h39e3cac_0
  pytest-astropy-0.5.0-py37_0
  pytest-doctestplus-0.3.0-py37_0
  pytest-openfiles-0.3.2-py37_0
  pytest-remotedata-0.3.1-py37_0

The following packages were DOWNGRADED:

  lzo                                       2.10-h49e0be7_2 --> 2.10-h7b6447c_2
  pycosat                              0.6.3-py37h14c3975_0 --> 0.6.3-py37h27cfd23_0
  sphinxcontrib-app~                             1.0.2-py_0 --> 1.0.2-pyhd3eb1b0_0
  sphinxcontrib-dev~                             1.0.2-py_0 --> 1.0.2-pyhd3eb1b0_0
  sphinxcontrib-htm~                             1.0.3-py_0 --> 1.0.3-pyhd3eb1b0_0
  sphinxcontrib-jsm~                             1.0.1-py_0 --> 1.0.1-pyhd3eb1b0_0
  sphinxcontrib-qth~                             1.0.3-py_0 --> 1.0.3-pyhd3eb1b0_0
  sphinxcontrib-ser~                             1.1.4-py_0 --> 1.1.4-pyhd3eb1b0_0

And now the script is not running:
python scvelo.run.cell.anno.L01cov.to.L22cov.py 
OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 555, in read_dataset
    dataset = dataset.asstr()
AttributeError: 'Dataset' object has no attribute 'asstr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scvelo.run.cell.anno.L01cov.to.L22cov.py", line 41, in <module>
    adata = scv.read("/home/ubuntu/L01cov_to_L22cov/L01cov_to_L22cov_filtered_cells.loom", sparse=True, cache=True)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/scanpy/readwrite.py", line 122, in read
    **kwargs,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/scanpy/readwrite.py", line 725, in _read
    return read_h5ad(path_cache)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 424, in read_h5ad
    d[k] = read_dataframe(f[k])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 159, in func_wrapper
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 487, in read_dataframe
    index=read_series(group[idx_key]),
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 159, in func_wrapper
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 516, in read_series
    return read_dataset(dataset)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/anndata/_io/utils.py", line 163, in func_wrapper
    f"Above error raised while reading key {elem.name!r} of "
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/obs/_index' of type <class 'h5py._hl.dataset.Dataset'> from /.

**Comment by WeilerP** [comment]
Hm, okay. So this problem originates from `anndata`. My suggestion would be the following: To rule out any problem due to conflicting package versions in your environment, I'd set up a new environment from scratch and run the script there:

```zsh
conda create -n ENV_NAME python=PYTHON_VERSION && conda activate ENV_NAME
pip install scvelo
python scvelo.run.cell.anno.L01cov.to.L22cov.py 
```

This way, only the necessary libraries should be installed and version conflicts should not exist. Would that be an option for you?

**Comment by somnathtagore** [comment]
Hi,
Thank you... i did the above (made a new conda env and installed scvelo again) and it works now.
Many thanks!

**Comment by WeilerP** [comment]
Great! So the problem seems to have been caused by incompatible package versions.
