### ISSUE TITLE
moments calculations failed in nopython mode pipeline

### ISSUE THREAD

**Issue by Laura19993** [theislab/scvelo#381]
When trying to execute `scv.pp.moments(adata, n_pcs=30, n_neighbors=30)` I get the error below. I am pretty new to python and any help is very much appreciated. Seems to be something about numba and not scVelo directly?
Thanks, Laura

```pytb
computing neighbors

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-10-f3bb6d041c5d> in <module>
      3 #and scv.pp.neighbors. First order is needed for deterministic velocity estimation, while stochastic
      4 #estimation also requires second order moments
----> 5 scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

~/.conda/envs/jupyter2/lib/python3.9/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, use_rep, use_highly_variable, copy)
     62 
     63     if n_neighbors is not None and n_neighbors > get_n_neighs(adata):
---> 64         neighbors(
     65             adata,
     66             n_neighbors=n_neighbors,

~/.conda/envs/jupyter2/lib/python3.9/site-packages/scvelo/preprocessing/neighbors.py in neighbors(adata, n_neighbors, n_pcs, use_rep, use_highly_variable, knn, random_state, method, metric, metric_kwds, num_threads, copy)
    161             warnings.simplefilter("ignore")
    162             neighbors = Neighbors(adata)
--> 163             neighbors.compute_neighbors(
    164                 n_neighbors=n_neighbors,
    165                 knn=knn,

~/.conda/envs/jupyter2/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    732                 X = pairwise_distances(X, metric=metric, **metric_kwds)
    733                 metric = 'precomputed'
--> 734             knn_indices, knn_distances, forest = compute_neighbors_umap(
    735                 X, n_neighbors, random_state, metric=metric, metric_kwds=metric_kwds)
    736             # very cautious here

~/.conda/envs/jupyter2/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors_umap(X, n_neighbors, random_state, metric, metric_kwds, angular, verbose)
    277     random_state = check_random_state(random_state)
    278 
--> 279     knn_indices, knn_dists, forest = nearest_neighbors(
    280         X, n_neighbors, random_state=random_state,
    281         metric=metric, metric_kwds=metric_kwds,

~/.conda/envs/jupyter2/lib/python3.9/site-packages/umap/umap_.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, low_memory, use_pynndescent, verbose)
    385                 if verbose:
    386                     print(ts(), "NN descent for", str(n_iters), "iterations")
--> 387                 knn_indices, knn_dists = nn_descent(
    388                     X,
    389                     n_neighbors,

~/.conda/envs/jupyter2/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~/.conda/envs/jupyter2/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~/.conda/envs/jupyter2/lib/python3.9/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fd8c4d6e3a0>.
Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (IS_OP) found

File "../../../../home/lwolbeck/.conda/envs/jupyter2/lib/python3.9/site-packages/umap/nndescent.py", line 38:
def init_rp_tree(data, dist, current_graph, leaf_array, tried=None):
    if tried is None:
    ^

During: resolving callee type: type(CPUDispatcher(<function init_rp_tree at 0x7fd8e03685e0>))
During: typing of call at /home/lwolbeck/.conda/envs/jupyter2/lib/python3.9/site-packages/umap/nndescent.py (199)

Enable logging at debug level for details.

File "../../../../home/lwolbeck/.conda/envs/jupyter2/lib/python3.9/site-packages/umap/nndescent.py", line 199:
def nn_descent(
    <source elided>
    if rp_tree_init:
        init_rp_tree(data, dist, current_graph, leaf_array, tried=tried)
        ^
```
#### Versions
scvelo==0.2.3  scanpy==1.7.1  anndata==0.7.5  loompy==3.0.6  numpy==1.20.1  scipy==1.6.1  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.2.3

**Comment by WeilerP** [comment]
Which version of numba are you using?

**Comment by Laura19993** [comment]
0.51.2

**Comment by WeilerP** [comment]
Okay, using Python 3.9 may be a problem here. A similar issue has previously been raised in scanpy [here](https://github.com/theislab/scanpy/issues/1652). Also, scvelo has only been tested under Python 3.7 and 3.8, so if you do not necessarily need to use Python 3.9, I suggest to switch to Python 3.7 or Python 3.8. Should you need to use Python 3.9, you can follow the suggestion in above mentioned issue and install the pre-release version of `numba`.
Let me know if you still encounter the more problems afterwards.

**Comment by Laura19993** [comment]
Thank you very much, it is working now when using python 3.8!
