### ISSUE TITLE
Issue with scv.pp.moments (trying to build an R pipeline Seurat --> scvelo)

### ISSUE THREAD

**Issue by france-hub** [theislab/scvelo#498]
Hi thank you for this package!

I am starting using scvelo. However I generally work in R (absolute beginner in Python) and I am trying to write a pipeline to use scvelo in R using reticulate. I am able to create successfully the adata object. the filter_and_normalize function works well but I am stucked at the next step. 

The following is my code in R. 

Summarizing I have loom files, I convert them into Seurat objects, subset the cells present in my already preprocessed Seurat object (CD8), extract the assays spliced, ambiguous and unspliced and add them to my Seurat object (CD8). Then I obtain the h5ad file and load it with scvelo.  

```
library(reticulate)
library(destiny)
library(Seurat)
library(SeuratData)
library(SeuratDisk)
library(anndata)
library(SeuratWrappers)

setwd("~/Documents/AML_project/scRNA_AMLproj")

#bash
#pip install -U scvelo
#conda activate r-velocity
#python
#>>>import scvelo as scv

use_condaenv("r-velocity", required = TRUE)
scv <- import("scvelo")

#Load in the loom files
ld.list <- list.files("velocity", pattern = "loom", all.files = TRUE)
ld <- lapply(ld.list, function(x){
  ReadVelocity(paste0("velocity/", x))
})

ld.list <- gsub(".loom", "_", ld.list)

#Trasform the loom files into Seurat and rename colnames for each object according to the cells names of the integrated Seurat object (CD8)
so <- lapply(ld, as.Seurat)
so <- lapply(so, function(x) RenameCells(x, new.names = gsub("x", "-1", colnames(x)), for.merge = T))
so <- lapply(so, function(y) RenameCells(y, new.names = gsub(".*:", "", colnames(y)), for.merge = T))
so <-  lapply(seq_along(ld.list), function(z) RenameCells(so[[z]], new.names = paste0(ld.list[[z]], colnames(so[[z]]))))

#Merge the objects
som <- merge(so[[1]], so[-(1)], merge.data = TRUE)

#Extract only the intersection between the Seurat integrated object (CD8) and the merged Seurat file
som <- som[, intersect(colnames(CD8), colnames(som[, colnames(CD8)]))]

#Create the specific assays
spliced <- CreateAssayObject(GetAssayData(som, assay = "spliced"))
unspliced <- CreateAssayObject(GetAssayData(som, assay = "unspliced"))
ambiguous <- CreateAssayObject(GetAssayData(som, assay = "ambiguous"))

#Import the assays in the original Seurat object (CD8)
CD8[["spliced"]] <- spliced
CD8[["unspliced"]] <- unspliced
CD8[["ambiguous"]] <- ambiguous

CD8[['RNA']] <- CD8[["spliced"]]

DefaultAssay(CD8) <- "RNA"

#Obtain the h5ad file
SaveH5Seurat(CD8, filename = "CD8scv.h5Seurat")
Convert("CD8scv.h5Seurat", dest = "h5ad")

#load in the h5ad file
adata <- scv$read("CD8scv.h5ad")

```
Adata seems to be correct:

```
adata

AnnData object with n_obs × n_vars = 15097 × 33538
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'sample_id', 'barcode', 'group_id', 'timepoint', 'RespTmp', 'ELN', 'batch', 'cxds_score', 'bcds_score', 'hybrid_score', 'sum', 'detected', 'subsets_Mt_sum', 'subsets_Mt_detected', 'subsets_Mt_percent', 'total', 'sum_drop', 'detected_drop', 'subsets_Mt_percent_drop', 'integrated_snn_res.0.1', 'integrated_snn_res.0.2', 'integrated_snn_res.0.4', 'integrated_snn_res.0.6', 'integrated_snn_res.0.8', 'integrated_snn_res.1', 'integrated_snn_res.1.2', 'integrated_snn_res.2', 'seurat_clusters', 'CTgene', 'CTnt', 'CTaa', 'CTstrict', 'Frequency', 'cloneType', 'T_CD81', 'integrated_snn_res.0.5', 'integrated_snn_res.0.7', 'integrated_snn_res.0.9', 'cluster_id', 'pt1', 'pt2', 'nCount_spliced', 'nFeature_spliced', 'nCount_unspliced', 'nFeature_unspliced', 'nCount_ambiguous', 'nFeature_ambiguous'
    var: 'features', 'ambiguous_features', 'spliced_features', 'unspliced_features'
    obsm: 'X_tsne', 'X_umap'
    layers: 'ambiguous', 'spliced', 'unspliced'
```
Then I try to plot a UMAP (it works) but when I try to run the dynamic model I get an error:

```
## get embedding
emb <- data.frame(adata$obsm['X_umap'])
clusters <- CD8@active.ident
rownames(emb) <- names(clusters)

## get clusters, convert to colors
col <- rainbow(length(levels(clusters)), s=0.8, v=0.8)
cell.cols <- col[clusters]
names(cell.cols) <- names(clusters)

## simple plot
par(mar=c(1,1,1,1))
plot(emb, col=cell.cols, pch=16,
     xlab='UMAP X', ylab='UMAP Y')
legend(x=4, y=-3.4, 
       legend=levels(clusters),
       col=col, 
       pch=16)

## run scvelo dynamic model
scv$pp$filter_and_normalize(adata, min_shared_counts = 20)
scv$pp$moments(adata)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "../../../miniconda3/lib/python3.8/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /home/francesco/miniconda3/lib/python3.8/site-packages/umap/layouts.py (52)

Detailed traceback:
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scvelo/preprocessing/moments.py", line 64, in moments
    neighbors(
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scvelo/preprocessing/neighbors.py", line 163, in neighbors
    neighbors.compute_neighbors(
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scanpy/neighbors/__init__.py", line 791, in compute_neighbors
    knn_indices, knn_distances, forest = compute_neighbors_umap
```

I have then tried to run all the steps from a data directly in Python and I get this: 
```
>>> scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
computing neighbors
Traceback (most recent call last):
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scvelo/preprocessing/moments.py", line 64, in moments
    neighbors(
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scvelo/preprocessing/neighbors.py", line 163, in neighbors
    neighbors.compute_neighbors(
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scanpy/neighbors/__init__.py", line 791, in compute_neighbors
    knn_indices, knn_distances, forest = compute_neighbors_umap(
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/scanpy/neighbors/__init__.py", line 301, in compute_neighbors_umap
    from umap.umap_ import nearest_neighbors
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/umap/umap_.py", line 54, in <module>
    from umap.layouts import (
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/umap/layouts.py", line 39, in <module>
    def rdist(x, y):
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/typed_passes.py", line 384, in run_pass
    lower.lower()
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/francesco/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/francesco/miniconda3/lib/python3.8/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "../../../miniconda3/lib/python3.8/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /home/francesco/miniconda3/lib/python3.8/site-packages/umap/layouts.py (52)
```
Do you have any suggestions? Apologize if I have been too long. 

Thanks

Francesco

**Comment by WeilerP** [comment]
@france-hub, could you please share the output of `scv.logging.print_versions()`? I am pretty sure you are using incompatible combination versions of `umap-learn` and `numba`. See e.g. #449.

On a general note: Please stick to the issue template. It makes debugging such issues much easier. Thanks!

**Comment by france-hub** [comment]
Thank you for your prompt answer. Downgrading numba to 0.52 solved the issue! 
Apologize if I didn't follow the template and if I didn't notice there was already a similar solved issue.
