### ISSUE TITLE
scv.pl.paga error,  'matplotlib.cbook' has no attribute 'iterable'

### ISSUE THREAD

**Issue by huipan1973** [theislab/scvelo#504]
I run scv.pl.paga and got the following error
AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'

```python
adata.uns["neighbors"]["distances"] = adata.obsp["distances"]
adata.uns["neighbors"]["connectivities"] = adata.obsp["connectivities"]
scv.tl.paga(adata, groups = "louvain")
scv.pl.paga(adata, basis = "umap", groupby = "louvain", save = "paga_graph.png")
```

<details>
<summary> Error </summary>

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panh/miniconda3/envs/bioinfo/lib/python3.8/site-packages/scvelo/plotting/paga.py", line 353, in paga
    _paga(adata, ax=ax, show=False, text_kwds=text_kwds, **paga_kwargs)
  File "/home/panh/miniconda3/envs/bioinfo/lib/python3.8/site-packages/scvelo/plotting/paga.py", line 629, in _paga
    sct = _paga_graph(
  File "/home/panh/miniconda3/envs/bioinfo/lib/python3.8/site-packages/scvelo/plotting/paga.py", line 889, in _paga_graph
    nx.draw_networkx_edges(
  File "/home/panh/miniconda3/envs/bioinfo/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 579, in draw_networkx_edges
    if not cb.iterable(width):
AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'
```
</details>

#### Versions:

scvelo==0.2.3  scanpy==1.7.2  anndata==0.7.6  loompy==2.0.16  numpy==1.20.2  scipy==1.6.3  matplotlib==3.4.1  sklearn==0.24.2  pandas==1.2.4
>

**Comment by WeilerP** [comment]
@huipan1973, which version of `networkx` are you using?

**Comment by huipan1973** [comment]
It's 2.3

**Comment by WeilerP** [comment]
Can you try updating to the lastest version (potentially also `matplotlib`)? I believe you need `networkx>=2.4`.

**Comment by huipan1973** [comment]
That works. It updated networkx to version 2.5.  
Thanks!
