### ISSUE TITLE
OSError [Errno 22] Invalid argument when using scv.tl.recover_dynamics()

### ISSUE THREAD

**Issue by wyvern114** [theislab/scvelo#536]
Hello, first thanks for this useful package. and here is my trouble, when I use scv.tl.recover_dynamics( ) in my data, there was a error  

```
>>>scv.tl.recover_dynamics(m_data)
        recovering dynamics (using 1/16 cores)
        Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
        exitcode = _main(fd, parent_sentinel)
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
        prepare(preparation_data)
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
       _fixup_main_from_path(data['init_main_from_path'])
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in 
      _fixup_main_from_path
    main_content = runpy.run_path(main_path,
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 264, in run_path
       code, fname = _get_code_from_file(run_name, path_name)
     File "C:\Users\wyvern114\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 234, in _get_code_from_file
       with io.open_code(decoded_path) as f:
 OSError: [Errno 22] Invalid argument: 'C:\\Users\\wyvern114\\PycharmProjects\\pythonProject\\<input>'
```

#### Versions:
```
> >>scv.version
        '0.2.3'
```
Thank you for your help!

**Comment by WeilerP** [comment]
@wyvern114 are you running this in a script, the console or in a Jupyter notebook? This seems to be a problem with Pycharm not scvelo. After briefly googling this, I found [this](https://youtrack.jetbrains.com/issue/PY-36151?_ga=2.155514488.2114045875.1626707089-101065318.1626707089) issue on jetbrains.

**Comment by xinyue-jxy** [comment]
Hello, 


It seems that I have some issues due to command scv.tl.recover_dynamics(), so I put my question here. Hope it wouldn't bother you so much. And thank you thislab for this very useful tool.

My question is : there is this error appears when I tried to apply the command with subtype cluster with this new dataset `adata=adata[adata.obs['louvain'].isin(['4', '15'])]`, but it was ok when I apply it to the whole dataset. For the information, I was running this command with the terminal of MacOs even thought I write my script in Pycharm.

**The error appears in the terminal:**

recovering dynamics (using 1/4 cores)

  0%|          | 0/243 [00:00<?, ?gene/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/xinyue/scRNA-seq_python/test.py", line 69, in <module>
    print(buildAnndataFromStarCurr(sys.argv[1]))
  File "/Users/xinyue/scRNA-seq_python/test.py", line 31, in buildAnndataFromStarCurr
    scv.tl.recover_dynamics(adata_a)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/scvelo/tools/dynamical_model.py", line 488, in recover_dynamics
    res = _parallelize(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/scvelo/tools/dynamical_model.py", line 1266, in wrapper
    queue = Manager().Queue()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "test.py", line 69, in <module>
    print(buildAnndataFromStarCurr(sys.argv[1]))
  File "test.py", line 31, in buildAnndataFromStarCurr
    scv.tl.recover_dynamics(adata_a)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/scvelo/tools/dynamical_model.py", line 488, in recover_dynamics
    res = _parallelize(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/scvelo/tools/dynamical_model.py", line 1266, in wrapper
    queue = Manager().Queue()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError


 If anyone can help me with this, or any suggestions, I'll take them all. thanks for your help!!

XIN

**Comment by WeilerP** [comment]
@Xin-jxy would please open a discussion for this? Would be the appropriate place and it is found easier instead of being hidden in this issue. Thanks!

**Comment by WeilerP** [comment]
@wyvern114, #541 might be informative/helpful for you as well.
