### ISSUE TITLE
scanpy 1.4.2 breaks pp.moments

### ISSUE THREAD

**Issue by agillen** [theislab/scvelo#58]
The new version of scanpy released today appears to break `scvelo.pp.moments` (and presumably much of scanpy itself). This is reproducible with the Dentate Gyrus example data. Full error (following the example vignette):

```
>>> scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
computing neighbors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scvelo/preprocessing/moments.py", line 45, in moments
    neighbors(adata, n_neighbors=n_neighbors, use_rep=use_rep, n_pcs=n_pcs, method=method, metric=metric)
  File "/usr/local/lib/python3.7/site-packages/scvelo/preprocessing/neighbors.py", line 82, in neighbors
    neighbors = Neighbors(adata)
  File "/usr/local/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 466, in __init__
    self.n_neighbors = int(self._distances.count_nonzero() / self._distances.shape[0])
AttributeError: 'NoneType' object has no attribute 'count_nonzero'
```

Rolling back to `scanpy` 1.4.1 solves the problem. @theislab - Filing this issue here rather than in the scanpy repo as I don't have a reproducible upstream example.

**Comment by VolkerBergen** [comment]
Thanks @agillen for raising this important issue.

@falexwolf Is that maybe related to the umap dependency in `neighbors`?

**Comment by falexwolf** [comment]
Don't do anything that expects `rp_forest`, as this is for now a development feature.

**Comment by falexwolf** [comment]
Don't do anything that expects `rp_forest` as this is for the time being a development feature.

**Comment by VolkerBergen** [comment]
Does `pp.neighbors` run well on your machine?

Apart from what has been noted above, I get the following error:


```
>>> sc.pp.neighbors(adata)

TypeError                                 Traceback (most recent call last)
<ipython-input-3-5d47edb05ae7> in <module>()
----> 1 sc.pp.neighbors(adata)

~/anaconda3/envs/py36/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, copy)
     92         n_neighbors=n_neighbors, knn=knn, n_pcs=n_pcs, use_rep=use_rep,
     93         method=method, metric=metric, metric_kwds=metric_kwds,
---> 94         random_state=random_state)
     95     adata.uns['neighbors'] = {}
     96     adata.uns['neighbors']['params'] = {'n_neighbors': n_neighbors, 'method': method}

~/anaconda3/envs/py36/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    649             # use dense distances
    650             self._distances, self._connectivities = compute_connectivities_umap(
--> 651                 knn_indices, knn_distances, self._adata.shape[0], self.n_neighbors)
    652         # overwrite the umap connectivities if method is 'gauss'
    653         # self._distances is unaffected by this

~/anaconda3/envs/py36/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    297                                           knn_indices=knn_indices, knn_dists=knn_dists,
    298                                           set_op_mix_ratio=set_op_mix_ratio,
--> 299                                           local_connectivity=local_connectivity)
    300     distances = get_sparse_matrix_from_indices_distances_umap(knn_indices, knn_dists, n_obs, n_neighbors)
    301 

TypeError: fuzzy_simplicial_set() got an unexpected keyword argument 'knn_indices'
```

**Comment by falexwolf** [comment]
How about updating UMAP?

@Koncopd, we should have checked this and thrown an error upon Scanpy import… Can you add this in `check_versions` in `scanpy/__init__.py`?

**Comment by Koncopd** [comment]
@falexwolf , @VolkerBergen 
Nothing was changed regarding the storage of distances.
https://github.com/theislab/scanpy/blob/fe623daee67096500fc0c54a1c3cffc6431c4d25/scanpy/neighbors/__init__.py#L455

**Comment by Koncopd** [comment]
So is this an error caused by an old version of umap?

**Comment by VolkerBergen** [comment]
I get this error with the latest version of umap-learn (v0.3.8) when installed via pip. Installing umap-learn via conda solves the issue..

**Comment by Koncopd** [comment]
@falexwolf @VolkerBergen there was a mistake, now it is fixed. Everything should work.
https://github.com/theislab/scanpy/commit/a69e0d16654eb5dc36881b66ef83fecd6a7d8511

**Comment by falexwolf** [comment]
> @falexwolf @VolkerBergen there was a mistake of mine, now it is fixed. Everything should work.
theislab/scanpy@a69e0d1

OK! We should make 1.4.3 asap in this case.

**Comment by VolkerBergen** [comment]
Thanks @Koncopd.
