### ISSUE TITLE
scv.pl.scatter() error during differential kinetics (using velocity genes and numeric Leiden clusters)

### ISSUE THREAD

**Issue by ACastanza** [theislab/scvelo#689]
I was working through the differential kinetics workflow but trying to select the genes using the velocity genes list instead of manually specifying a handful of candidate genes. When running the function to scatter plot the genes from the differential kinetics calculation after the "diff_clusters" step, the scv.pl.scatter function is returning an error.

```python

scv.tl.differential_kinetic_test(adata, groupby=cluster_type)
scv.get_df(adata[:, velocity_genes_list], ['fit_diff_kinetics', 'fit_pval_kinetics'], precision=2)
                   fit_diff_kinetics  fit_pval_kinetics
ENSG00000164951.16              3,14           2.78e-03
ENSG00000124225.16                14           1.05e-04
ENSG00000101752.12                 3           2.58e-07
ENSG00000150938.10                 3           2.64e-06
ENSG00000187098.17             10,15           2.32e-03
...                              ...                ...
ENSG00000144857.14             10,15           2.05e-08
ENSG00000213928.9                  3           6.57e-17
ENSG00000107371.14                14           1.38e-23
ENSG00000067141.17                 3           3.20e-05
ENSG00000114948.13                 3           3.04e-05

diff_clusters=list(adata[:, velocity_genes_list].var['fit_diff_kinetics'])
>>> diff_clusters
['3,14', '14', '3', '', '3', '10,15', '1,13', '', '3', '10,15', '3', '1,10', '1', '6', '', '3', '16', '', '1,14', '1,10,13,15', '3', '3', '1,10', '16', '16', '16', '3', '10,15', '', '1,13', '', '3,15', '3,14', '3,14', '1,13', '4,14', '1,3,10,13,16', '1,10,13', '16', '16', '1,13', '10', '14', '14', '16', '3', '16', '16', '1,13', '14', '2,7,9,11', '', '3', '6', '13,14', '1,2,4,13', '3', '3,6,10,15', '1,13', '10,15', '16', '14', '3', '10', '14', '16', '3', '3,14', '7', '14', '16', '1', '3', '3', '3', '3', '16', '2,3,16', '10', '15', '3', '3', '16', '14', '0,5,12', '3', '', '14', '16', '3', '6', '', '3', '3', '16', '0,1,5,10', '3', '10,15', '14', '0,3', '10', '16', '3', '3,14', '14', '10,15', '0,1,2,3,6,8,12', '3,10', '3', '13', '16', '1,3,10,13,15', '3', '16', '', '3', '14', '3', '1,3', '3,10,14,15', '10,15', '3,10,15', '1', '10', '', '14', '', '3,14', '', '3', '10', '14', '16', '0,5,6,12', '16', '15', '3', '16', '14', '2,3,14', '3', '16', '14', '3', '16', '1,3,10', '3,5,14', '3,14', '3', '15', '3', '1', '10', '15', '1,3,13', '3', '3', '14', '10', '7,9,11', '0,3', '16', '1,12,13', '1,3,13,15', '10,16', '16', '16', '16', '3', '1,10', '3', '14', '3', '3,14', '16', '14', '16', '3,14', '14', '10', '16', '3,14', '14', '3', '14', '1,13', '1,13', '3', '10', '10,15', '2', '1,13', '14', '2', '7,9', '10,14', '14', '3', '14', '1,10,13,16', '3', '3', '2,14', '2', '2,7,8,9,11', '1,3', '3,14', '14', '14', '14', '1,13', '16', '14', '1,3,15', '2', '', '3,14', '3', '10,15', '3', '14', '3', '3']

# Numeric cluster IDs are expected because this was run with `sanpy.tl.leiden(adata)` and manual cluster names have not been assigned, but then when running 

scv.pl.scatter(adata, legend_loc='right', size=60, title='diff kinetics',
               add_outline=diff_clusters, outline_width=(.8, .2))

Traceback (most recent call last):
```

<details>

<summary> Error output </summary>

```pytb
scv.pl.scatter(adata, legend_loc='right', size=60, title='diff kinetics',
               add_outline=diff_clusters, outline_width=(.8, .2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/scvelo/plotting/scatter.py", line 636, in scatter
    if idx is not None and np.sum(idx) > 0:  # if anything to be outlined
TypeError: '>' not supported between instances of 'str' and 'int'
```
</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.4  scanpy==1.8.1  anndata==0.7.6.dev49+g19ba44d  loompy==2.0.16  numpy==1.19.2  scipy==1.7.1  matplotlib==3.4.2  sklearn==0.24.2  pandas==1.2.4
```
</details>

**Comment by WeilerP** [comment]
Looks awful similar to #674. @ACastanza, could you please check if passing `color` fixes the issue?

**Comment by ACastanza** [comment]
Oh! Yes, that did fix it! Thanks! If its supposed to detect the clustering to color by automatically it was probably failing because the clustering in my dataset was under `adata.obs['leiden']`
If it's not supposed to autodetect in that function, it might be good to get that particular command in the Differential Kinetics vignette updated.

**Comment by WeilerP** [comment]
Agreed. There should be a check that both arguments are provided.
