### ISSUE TITLE
Error in scv.tl.velocity after recover dynamics if initial velocity was stochastic

### ISSUE THREAD

**Issue by ACastanza** [theislab/scvelo#712]
Hello,
I'm not entirely sure this is actually a bug, it depends on what the exact intended logic is with the effect of recovering dynamics.
If the initial scvelo.tl.velocity() is run with mode="stochastic" then even if you run scvelo.tl.recover_dynamics() separately, scvelo.tl.velocity(..., diff_kinetics=True)) errors after scv.tl.differential_kinetic_test unless the mode parameter matches the initial run. The reason I'm not sure if this is an error or not is because if the intent is specifically to modify the original embedding to incorporate the information from differential kinetics, then an error seems appropriate (although the specific error is odd), however, if the intent is to construct an alternate differential-kinetics aware dynamical embedding, or to switch the embedding mode, then this would be an error.

Fails:
```python
# Dataset was prerpocessed with scanpy
adata = anndata.read_h5ad(options.input_file)
sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=2000, check_values=False)
scv.pp.filter_and_normalize(adata, min_shared_counts=30, n_top_genes=2000, layers_normalize={'spliced', 'unspliced'})
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata) ## Dynamics are always recovered because they're needed for differential_kinetic_test and that can't run with specifying n_jobs so we do it here
scv.tl.velocity(adata, mode='stochastic') ## Running in stochastic mode since that seems to better match the biology for  raw reanalysis of the pancreas data
scv.tl.velocity_graph(adata)
scv.tl.velocity_pseudotime(adata)
sc.tl.leiden(adata)

scv.tl.differential_kinetic_test(adata, groupby=leiden) ## specifying leiden clusters since clusters were generated from scratch and don't exist under 'clusters'
kwargs = dict(linewidth=2, add_linfit=True, frameon=False)
scv.tl.velocity(adata, mode='dynamical', diff_kinetics=True) ## Dynamical mode fails even though dynamics were recovered earlier, mode = 'stochastic' works, or setting mode='dynamical' earlier works see below.

```

Works:
```python
adata = anndata.read_h5ad(options.input_file)
sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=2000, check_values=False)
scv.pp.filter_and_normalize(adata, min_shared_counts=30, n_top_genes=2000, layers_normalize={'spliced', 'unspliced'})
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata) ## Always recovering dynamics for later to enable multicore support
scv.tl.velocity(adata, mode='stochastic') ## stochastic mode
scv.tl.velocity_graph(adata)
scv.tl.velocity_pseudotime(adata)
sc.tl.leiden(adata)

scv.tl.differential_kinetic_test(adata, groupby=leiden)
kwargs = dict(linewidth=2, add_linfit=True, frameon=False)
scv.tl.velocity(adata, mode='stochastic', diff_kinetics=True)  ## Also stochastic mode
```

also works:

```python
adata = anndata.read_h5ad(options.input_file)
sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=2000, check_values=False)
scv.pp.filter_and_normalize(adata, min_shared_counts=30, n_top_genes=2000, layers_normalize={'spliced', 'unspliced'})
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata) ## Always recovering dynamics for later to enable multicore support
scv.tl.velocity(adata, mode='dynamical') ## Dynamical mode
scv.tl.velocity_graph(adata)
scv.tl.velocity_pseudotime(adata)
sc.tl.leiden(adata)

scv.tl.differential_kinetic_test(adata, groupby=leiden)
kwargs = dict(linewidth=2, add_linfit=True, frameon=False)
scv.tl.velocity(adata, mode='dynamical', diff_kinetics=True) ## Also Dynamical mode (matching modes)
```

<details>
The error is returning from here: https://github.com/theislab/scvelo/blob/master/scvelo/tools/velocity.py#L455

This makes sense because 'clusters' is not in my dataset, the dataset clusters are under 'leiden' because the clustering was run with the leiden algorithm however because differential_kinetics was run, it shouldn't be triggering that else statement and looking for 'clusters'. **(That said, the ability to pass a clusters="xyz" parameter to scvelo.tl.velocity() would be welcome to accommodate other clustering methods.)**

<summary> Error output </summary>

```pytb
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'clusters'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/gpbeta_2/gp_home/taskLib/scVelo.ComputeVelocity.1.1978/compute_scvelo.py", line 254, in <module>
    main()
  File "/opt/gpbeta_2/gp_home/taskLib/scVelo.ComputeVelocity.1.1978/compute_scvelo.py", line 195, in main
    scv.tl.velocity(adata, mode='dynamical', diff_kinetics=True)
  File "/opt/conda/lib/python3.8/site-packages/scvelo/tools/velocity.py", line 445, in velocity
    clusters = adata.obs[groupby]
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'clusters'

```
</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.3  scanpy==1.7.2  anndata==0.7.6  loompy==3.0.6  numpy==1.19.2  scipy==1.5.3  matplotlib==3.4.3  sklearn==0.24.2  pandas==1.2.2
```
</details>

In follow up to: https://github.com/theislab/scvelo/discussions/705

**Comment by WeilerP** [comment]
@ACastanza, thanks for opening the issue! @VolkerBergen, do you already happen to have any thoughts on this?
