### ISSUE TITLE
sct.pl.velocity not producing plots

### ISSUE THREAD

**Issue by jvelghe** [theislab/scvelo#731]
For some reason I can plot everything except the gene-specific plots through the function sct.pl.velocity. I get errors mostly relating to the graphics, either in the gridspec.py file (below) which I tried to debug. Then I got other errors relating to nrows/ncols, or a plot that was just blank. 

Any help would be appreciated, and I've put the code in starting from where the errors began. 
...

```python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import anndata
>>> import scvelo as scv
>>> import pandas as pd
>>> import numpy as np
>>> import matplotlib
>>> import matplotlib.pyplot as plt
>>> import re
>>> csv_files = "/Users/janievelghe1/Desktop/helena/sc_velo_miniproject/data/csv_files/"
>>> loom_files = "/Users/janievelghe1/Desktop/helena/sc_velo_miniproject/results/scvelo_loom/"
>>> results = "/Users/janievelghe1/Desktop/helena/sc_velo_miniproject/results/"
>>> adata = scv.read(results + "scvelo_loom/processed_adata_2.loom")
>>> # compute pca and neighbours --> for velocity estimation
... scv.pp.moments(adata, n_pcs = 30, n_neighbors = 30)
computing neighbors
    finished (0:00:30) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:08) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
>>> # estimate velocity and project into lower dimension for plotting
... scv.tl.velocity(adata)
computing velocities
    finished (0:00:30) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
```

<details>

<summary> Error output 
</summary>

```pytb
# >>> scv.pl.velocity(adata, var_names=['INS', 'GCG', 'SST', 'IAPP'], show = True) #results + "scvelo_vel.png"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/janievelghe1/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/scvelo/plotting/velocity.py", line 152, in velocity
    gs = pl.GridSpec(nrows, ncols, wspace=0.5, hspace=0.8)
  File "/Users/janievelghe1/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/matplotlib/gridspec.py", line 422, in __init__
    height_ratios=height_ratios)
  File "/Users/janievelghe1/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/matplotlib/gridspec.py", line 49, in __init__
    f"Number of rows must be a positive integer, not {nrows}")
ValueError: Number of rows must be a positive integer, not 0
```
</details>

<details> <summary> Versions </summary>

```pytb
Running scvelo 0.2.4 (python 3.6.10) on 2021-10-18 12:12.
```
</details>

**Comment by WeilerP** [comment]
@jvelghe, you are loading a file `processed_adata_2.lomm` and do not filter and normalize in above code, so I assumed this was the already filtered, normalized and log1p-transformed data. You should **not** skip the filter and normalize step.
The gene names are stored in `adata.var_names`.
I'll close this issue for now since it seems to be either a duplicate or simply behavior as it should be expected when genes are not present. Feel free to come back with further questions. If needed, we can reopen the issue again.
