### ISSUE TITLE
Running the velocity_graph function produces an error

### ISSUE THREAD

**Issue by paulitikka** [theislab/scvelo#746]
Hi,

I have run scv.tl.velocity_graph(adata) to my data, but it produces an error (see below).
I have reproduced it several times with my pipeline and data, which seem to work ok by that far. 
Nevertheless, could you help me to solve this please? Thank you.

B.r., Pauli

The error:

runcell("And now... let's see...", 'D:/Codes and Instructions/splitted_tikka51121.py')
computing velocity graph (using 1/20 cores)
HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=5582.0), HTML(value='')))

WARNING: saving figure to file figures\umap_celltypesnoo.pdf

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Hyapp\Anaconda3-2020.11\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Hyapp\Anaconda3-2020.11\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Hyapp\Anaconda3-2020.11\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Codes and Instructions\splitted_tikka51121.py", line 104, in <module>
    scv.tl.velocity_graph(adata) #need to solve this freezing..
  File "C:\Hyapp\Anaconda3-2020.11\lib\site-packages\scvelo\tools\velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "C:\Hyapp\Anaconda3-2020.11\lib\site-packages\scvelo\tools\velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "C:\Hyapp\Anaconda3-2020.11\lib\site-packages\scvelo\core\_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Hyapp\Anaconda3-2020.11\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

#My pipeline:
import scanpy as sc
import sys
import numpy as np
import anndata
import scvelo as scv #Installed the most recent one..
import matplotlib as plt
import pandas as pd
import os
import loompy
import multiprocessing
from multiprocessing import Process
import time #this could also work.. https://smorabit.github.io/tutorials/8_velocyto/
os.chdir(path='D:/Data for Seurat Analysis/filtered_gene_bc_matrices/Data Filtered and Processed in Seurat')
rspliced = pd.read_csv("rspliced3.csv")
runspliced=pd.read_csv("runspliced2.csv")
rpca=pd.read_csv("pca.csv")
rtsne=pd.read_csv("tsne.csv")
rumap=pd.read_csv("umap.csv") 
rspliced=rspliced.set_index('Unnamed: 0')
runspliced=runspliced.set_index('Unnamed: 0')
rpca=rpca.set_index('Unnamed: 0')
rtsne=rtsne.set_index('Unnamed: 0')
rumap=rumap.set_index('Unnamed: 0')
adata = anndata.AnnData(X = rspliced, 
                        layers = dict(spliced = rspliced, unspliced = runspliced),
                        obsm = dict(X_pca = rpca, X_tsne = rtsne, X_umap=rumap))
plt.use('AGG')
scv.settings.set_figure_params('scvelo')
scv.pl.proportions(adata)
scv.utils.show_proportions(adata) 
scv.pp.filter_genes(adata, min_shared_counts = 30)
scv.pp.normalize_per_cell(adata, enforce = True)
scv.pp.filter_genes_dispersion(adata, n_top_genes = 2000)
scv.pp.log1p(adata) #was this in the previous?
sc.pl.umap(adata,  frameon=False, legend_loc='on data', title='', save='_celltypesnoo.pdf')
scv.pp.neighbors(adata)
scv.pp.moments(adata) 
scv.tl.velocity(adata)
scv.tl.velocity_graph(adata)

#Here is my data, am I missing anything, and if yes how to add to anndata? 
adata
Out[...]: 
AnnData object with n_obs × n_vars = 5582 × 2000
    obs: 'initial_size_spliced', 'initial_size_unspliced', 'initial_size', 'n_counts'
    var: 'gene_count_corr', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'velocity_gamma', 'velocity_qreg_ratio', 'velocity_r2', 'velocity_genes'
    uns: 'neighbors', 'velocity_params'
    obsm: 'X_pca', 'X_tsne', 'X_umap'
    layers: 'spliced', 'unspliced', 'Ms', 'Mu', 'velocity', 'variance_velocity'
    obsp: 'distances', 'connectivities'

**Comment by paulitikka** [comment]
I got this solved to some extent. I installed same python and scvelo versions (3.8.10 and 0.2.4 with newest dependencies) that I had in my unix system (Ubuntu 20.04). I also updated my conda, but not sure if that helped. Then I still run issue with running the function if I ran it in Spyder's 'cell', so I tested to just run it separately, and it worked. The same applies also for scvelo.tl.recover_dynamics() and scv.get_df functions. The latter (scv.get_df had also erronously adata as it should have had df in the vignette: https://scvelo.readthedocs.io/DynamicalModeling/. In addition, I wonder if the writers of the scvelo package could also update the vignette describing what data types are needed for each 'adata' object? I had to change my cluster data as follows: adata.obs=adata.obs.astype('category') so that I could use scv.tl.rank_velocity_genes(adata, groupby='clusters', min_corr=.3) and scv.pl.proportions(adata, save='proportions.png') functions? Thank you.

**Comment by WeilerP** [comment]
@paulitikka, sorry for getting back to you only now. Regarding the original problem: I do not have a Windows machine on which I could investigate this issue. @michalk8, do you happen to know why this is failing on Windows and how to fix the issue?

> The latter (scv.get_df) had also erronously adata as it should have had df in the vignette: https://scvelo.readthedocs.io/DynamicalModeling/.

Sorry, not sure what you mean. Could you please open a separate issue including more details, _i.e._, a code snippet I can copy and paste, (potential) error message and package versions you are using?

> In addition, I wonder if the writers of the scvelo package could also update the vignette describing what data types are needed for each 'adata' object? I had to change my cluster data as follows: adata.obs=adata.obs.astype('category') so that I could use scv.tl.rank_velocity_genes(adata, groupby='clusters', min_corr=.3) and scv.pl.proportions(adata, save='proportions.png') functions?

Same as for the previous issue with `get_df`: Please open a separate issue with a detailed description (which tutorial you are running), code snippet, error message and package versions used. Thanks!

**Comment by michalk8** [comment]
> @paulitikka, sorry for getting back to you only now. Regarding the original problem: I do not have a Windows machine on which I could investigate this issue. @michalk8, do you happen to know why this is failing on Windows and how to fix the issue?

@paulitikka I assume you run a script (by seeing `Instructions/splitted_tikka51121.py` file) instead of a notebook.
Is your code wrapped in `if __name__ == '__main__'`? E.g.:
```python
if __name__ == '__main__':
    adata = ...
    ...
    scv.tl.velocity_graph(adata)
```
Here's a specific [SO answer}(https://stackoverflow.com/questions/24374288/where-to-put-freeze-support-in-a-python-script) why it's necessary to do so on Windows, when using ``multiprocessing``.

**Comment by HOXINO-Nana** [comment]
Hi All,

I'm having a similar issue that happens both when I use my own file and the tutorial file (pancreas). I'm running .py file in the terminals. I'm using MacOS Ventura 13.5 with M2 chip. 

My Error shows as,
`macbook-air:RNA_velocity jingnaxue$ python3 pancreas_data_trial.py
Filtered out 20801 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Extracted 2000 highly variable genes.
Logarithmized X.
computing neighbors
    finished (0:00:03) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/8 cores)
  0%|          | 0/3696 [00:00<?, ?cells/s]
Filtered out 20801 genes that are detected 20 counts (shared).
Normalized count data: X, spliced, unspliced.
Extracted 2000 highly variable genes.
Logarithmized X.
computing neighbors
    finished (0:00:02) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/8 cores)
  0%|          | 0/3696 [00:00<?, ?cells/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jingnaxue/Downloads/RNA_velocity/pancreas_data_trial.py", line 10, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
          ^^^^^^^^^^^^
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
            ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py", line 563, in start
    self._process.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/jingnaxue/Downloads/RNA_velocity/pancreas_data_trial.py", line 10, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
          ^^^^^^^^^^^^
  File "/Users/jingnaxue/Library/Python/3.11/lib/python/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
            ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py", line 567, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 382, in _recv
    raise EOFError
EOFError`


Does anyone know how to fix this problem? I also tried on intel chip and it showed up the same thing. 

Thank you so much.
