### ISSUE TITLE
tl.recover_dynamics gets killed due to excess memory usage

### ISSUE THREAD

**Issue by nagendraKU** [theislab/scvelo#756]
I am trying to run recover_dynamics on anndata of size 123472 x 37659. Because it was crashing in Jupyter notebook due to excessive memory usage (40 cores, 180 gb RAM node), I tried running it as a batch job on a high-memory node (40 cores, 1.5 TB RAM).

Still, the job gets terminated due to high memory usage. How can I fix this ?

```python
scv.pp.moments(adata, use_rep='X_scVI')
scv.tl.recover_dynamics(adata, n_jobs=40)


computing neighbors
    finished (0:01:04) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:07:06) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
recovering dynamics (using 40/40 cores)
  0%|          | 0/1692 [00:00<?, ?gene/s]

```

<details>

<summary> Jupyter notebook and batch submission error messages </summary>

```pytb

**Jupyter notebook error **

OSError                                   Traceback (most recent call last)
/scratch/33705989/ipykernel_21639/1753006312.py in <module>
----> 1 get_ipython().system('top')

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/ipykernel/zmqshell.py in system_piped(self, cmd)
    635                 self.user_ns['_exit_code'] = system(cmd)
    636         else:
--> 637             self.user_ns['_exit_code'] = system(self.var_expand(cmd, depth=1))
    638 
    639     # Ensure new system_piped implementation is used

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/IPython/utils/_process_posix.py in system(self, cmd)
    155                 child = pexpect.spawnb(self.sh, args=['-c', cmd]) # Pexpect-U
    156             else:
--> 157                 child = pexpect.spawn(self.sh, args=['-c', cmd])  # Vanilla Pexpect
    158             flush = sys.stdout.flush
    159             while True:

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/pexpect/pty_spawn.py in __init__(self, command, args, timeout, maxread, searchwindowsize, logfile, cwd, env, ignore_sighup, echo, preexec_fn, encoding, codec_errors, dimensions, use_poll)
    203             self.name = '<pexpect factory incomplete>'
    204         else:
--> 205             self._spawn(command, args, preexec_fn, dimensions)
    206         self.use_poll = use_poll
    207 

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/pexpect/pty_spawn.py in _spawn(self, command, args, preexec_fn, dimensions)
    302 
    303         self.ptyproc = self._spawnpty(self.args, env=self.env,
--> 304                                      cwd=self.cwd, **kwargs)
    305 
    306         self.pid = self.ptyproc.pid

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/pexpect/pty_spawn.py in _spawnpty(self, args, **kwargs)
    313     def _spawnpty(self, args, **kwargs):
    314         '''Spawn a pty and return an instance of PtyProcess.'''
--> 315         return ptyprocess.PtyProcess.spawn(args, **kwargs)
    316 
    317     def close(self, force=True):

/home/projects/xxx_user/pysc/lib/python3.7/site-packages/ptyprocess/ptyprocess.py in spawn(cls, argv, cwd, env, echo, preexec_fn, dimensions, pass_fds)
    228 
    229         if use_native_pty_fork:
--> 230             pid, fd = pty.fork()
    231         else:
    232             # Use internal fork_pty, for Solaris

/home/projects/xxx_user/pysc/lib/python3.7/pty.py in fork()
     95 
     96     master_fd, slave_fd = openpty()
---> 97     pid = os.fork()
     98     if pid == CHILD:
     99         # Establish a new session.

OSError: [Errno 12] Cannot allocate memory

**Batch job submission error **

Traceback (most recent call last):
  File "velocity_calc.py", line 19, in <module>
    scv.tl.recover_dynamics(adata, n_jobs=40)
  File "/home/projects/xxx_user/pysc/lib/python3.7/site-packages/scvelo/tools/dynamical_model.py", line 521, in recover_dynamics
    **kwargs,
  File "/home/projects/xxx_user/pysc/lib/python3.7/site-packages/scvelo/core/_parallelize.py", line 135, in wrapper
    for i, cs in enumerate(collections)
  File "/home/projects/xxx_user/pysc/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/projects/xxx_user/pysc/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/projects/xxx_user/pysc/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/projects/xxx_user/pysc/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/projects/xxx_user/pysc/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
```
</details>

<details> <summary> scvelo==0.2.4</summary>

```pytb
scvelo==0.2.4
```
</details>

**Comment by WeilerP** [comment]
@nagendraKU, this is a known issue. See e.g. [here](https://github.com/theislab/scvelo/issues/756) for the currently open issue and suggestions on how to possibly resolve the issue. You can reduce the size of your AnnData to only contain the minimal required slots and may want to reduce the number of cores used as well.

**Comment by spkhowe** [comment]
@WeilerP Can you point me to the duplicate issue? Having the same problem right now. Thanks.
