### ISSUE TITLE
scv.pl.proportions(): numpy.AxisError

### ISSUE THREAD

**Issue by jiangpuxuan** [theislab/scvelo#851]
I am new to use python to anlyze scRNA-seq. I run the `cellrank` workflow and always found this error.
Here is my code for `Cellrank`:
```import sys

import scvelo as scv
import scanpy as sc
import cellrank
import numpy as np

scv.settings.verbosity = 3
scv.settings.set_figure_params("scvelo")
cellrank.settings.verbosity = 2

import warnings

warnings.simplefilter("ignore", category=UserWarning)
warnings.simplefilter("ignore", category=FutureWarning)
warnings.simplefilter("ignore", category=DeprecationWarning)

adata =  sc.read_h5ad('./my.h5ad') # my data
scv.pl.proportions(adata)

```
The errorcode:
```
>>> scv.pl.proportions(adata)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\scvelo\plotting\proportions.py", line 88, in proportions
    np.mean(counts_layers, axis=1),
  File "<__array_function__ internals>", line 5, in mean
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 3372, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_methods.py", line 147, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_methods.py", line 66, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis 1 is out of bounds for array of dimension 1


```

I tried to use `SeuratDisk` or `loom` to get `h5ad` from a `seurat` object. I thought that must be some problem in this progress. 

Here is the anndata object from tutorial:
```
>>> adata
AnnData object with n_obs × n_vars = 2531 × 27998
    obs: 'day', 'proliferation', 'G2M_score', 'S_score', 'phase', 'clusters_coarse', 'clusters', 'clusters_fine', 'louvain_Alpha', 'louvain_Beta', 'palantir_pseudotime'
    var: 'highly_variable_genes'
    uns: 'clusters_colors', 'clusters_fine_colors', 'day_colors', 'louvain_Alpha_colors', 'louvain_Beta_colors', 'neighbors', 'pca'
    obsm: 'X_pca', 'X_umap'
    layers: 'spliced', 'unspliced'
    obsp: 'connectivities', 'distances'

```
Here is mine:
```
>>> adata
AnnData object with n_obs × n_vars = 5443 × 18489
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.0.8', 'seurat_clusters', 'SCT_snn_res.0.5', 'SCT_snn_res.0.6',
 'SCT_snn_res.0.7', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'new.ident', 'nCount_MAGIC_RNA', 'nFeature_MAGIC_RNA'
    var: 'SCT_features', '_index', 'features'
    obsm: 'X_tsne', 'X_umap'
    layers: 'SCT'

```

So, What packages or protocols should I follow to convert a seurat into a h5ad?
Thank you for your help!

**Comment by jiangpuxuan** [comment]
Sorry, I FOUND that my `anndata` object does not have `spliced` layer at all ! Now I tried to add it by `alvein-fry`

**Comment by WeilerP** [comment]
@jiangpuxuan, I'm closing this for now as the missing layers seem to be the problem. Happy to reopen if the issue persists when the corresponding layers have been added.
