### ISSUE TITLE
CI fails due to incompatible versions of `black` and `pre-commit`

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#854]
## Description

The linit checking step in the CI fails with specified versions of `pre-commit` and `black` with

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repofpjqa5l5/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repofpjqa5l5/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repofpjqa5l5/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repofpjqa5l5/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by WeilerP** [comment]
Closed via #855.
