### ISSUE TITLE
Unable to load loom files converted from Seurat

### ISSUE THREAD

**Issue by yojetsharma** [theislab/scvelo#919]
Hi, I am following this [10x trajectory analyses pipeline](https://www.10xgenomics.com/resources/analysis-guides/trajectory-analysis-using-10x-Genomics-single-cell-gene-expression-data ) for my dataset. I managed to convert my unspliced/spliced data using velocyto and also managed to load it using the scv.read function. 
According to pipeline, we can either directly load the 'filtered-bc-matrix' or we can load the processed seurat files which already has all the data regarding UMAP, clustering etc. Since, I have carried out all my analyses using seurat, I prefer to directly load the seurat files that I converted to loom object. But I am getting the following error:
```
>>> ls003 = scv.read_loom('/home/praghu/yojetsharma/new/loom_files/ls003/ls003.loom')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/anndata/compat/__init__.py", line 305, in inner_f
    return f(*args, **kwargs)
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/anndata/_io/read.py", line 251, in read_loom
    with connect(filename, "r", **kwargs) as lc:
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/loompy/loompy.py", line 1515, in connect
    return LoomConnection(filename, mode, validate=validate)
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/loompy/loompy.py", line 85, in __init__
    if not lv.validate(filename):
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/loompy/loom_validator.py", line 50, in validate
    self.version = get_loom_spec_version(f)
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/loompy/utils.py", line 19, in get_loom_spec_version
    if "attrs" in f and "LOOM_SPEC_VERSION" in f["/attrs"]:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/praghu/yojetsharma/.conda/envs/yojet_velo/lib/python3.10/site-packages/h5py/_hl/group.py", line 483, in __contains__
    return self._e(name) in self.id
  File "h5py/h5g.pyx", line 466, in h5py.h5g.GroupID.__contains__
  File "h5py/h5g.pyx", line 467, in h5py.h5g.GroupID.__contains__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 540, in h5py.h5g._path_valid
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 212, in h5py.h5l.LinkProxy.exists
RuntimeError: Unable to get link info (addr overflow, addr = 12416, size = 176, eoa = 2048)
```

**Comment by WeilerP** [comment]
This is an issue with AnnData/loompy. Please open an issue there.
